<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
	/**
	* Run the database seeds.
	*
	* @return void
	*/
	public function run() {
		
		DB::table('countries')->delete();
		
		$countries = array(
		  array('id' => '1','name' => 'Aruba'),
		  array('id' => '2','name' => 'Afghanistan'),
		  array('id' => '3','name' => 'Angola'),
		  array('id' => '4','name' => 'Anguilla'),
		  array('id' => '5','name' => 'Albania'),
		  array('id' => '6','name' => 'Andorra'),
		  array('id' => '7','name' => 'Netherlands Antilles'),
		  array('id' => '8','name' => 'United Arab Emirates'),
		  array('id' => '9','name' => 'Argentina'),
		  array('id' => '10','name' => 'Armenia'),
		  array('id' => '11','name' => 'American Samoa'),
		  array('id' => '12','name' => 'Antarctica'),
		  array('id' => '13','name' => 'French Southern territories'),
		  array('id' => '14','name' => 'Antigua and Barbuda'),
		  array('id' => '15','name' => 'Australia'),
		  array('id' => '16','name' => 'Austria'),
		  array('id' => '17','name' => 'Azerbaijan'),
		  array('id' => '18','name' => 'Burundi'),
		  array('id' => '19','name' => 'Belgium'),
		  array('id' => '20','name' => 'Benin'),
		  array('id' => '21','name' => 'Burkina Faso'),
		  array('id' => '22','name' => 'Bangladesh'),
		  array('id' => '23','name' => 'Bulgaria'),
		  array('id' => '24','name' => 'Bahrain'),
		  array('id' => '25','name' => 'Bahamas'),
		  array('id' => '26','name' => 'Bosnia and Herzegovina'),
		  array('id' => '27','name' => 'Belarus'),
		  array('id' => '28','name' => 'Belize'),
		  array('id' => '29','name' => 'Bermuda'),
		  array('id' => '30','name' => 'Bolivia'),
		  array('id' => '31','name' => 'Brazil'),
		  array('id' => '32','name' => 'Barbados'),
		  array('id' => '33','name' => 'Brunei'),
		  array('id' => '34','name' => 'Bhutan'),
		  array('id' => '35','name' => 'Bouvet Island'),
		  array('id' => '36','name' => 'Botswana'),
		  array('id' => '37','name' => 'Central African Republic'),
		  array('id' => '38','name' => 'Canada'),
		  array('id' => '39','name' => 'Cocos (Keeling) Islands'),
		  array('id' => '40','name' => 'Switzerland'),
		  array('id' => '41','name' => 'Chile'),
		  array('id' => '42','name' => 'China'),
		  array('id' => '43','name' => 'CÃ´te dâ€™Ivoire'),
		  array('id' => '44','name' => 'Cameroon'),
		  array('id' => '45','name' => 'Congo, The Democratic Republic'),
		  array('id' => '46','name' => 'Congo'),
		  array('id' => '47','name' => 'Cook Islands'),
		  array('id' => '48','name' => 'Colombia'),
		  array('id' => '49','name' => 'Comoros'),
		  array('id' => '50','name' => 'Cape Verde'),
		  array('id' => '51','name' => 'Costa Rica'),
		  array('id' => '52','name' => 'Cuba'),
		  array('id' => '53','name' => 'Christmas Island'),
		  array('id' => '54','name' => 'Cayman Islands'),
		  array('id' => '55','name' => 'Cyprus'),
		  array('id' => '56','name' => 'Czech Republic'),
		  array('id' => '57','name' => 'Germany'),
		  array('id' => '58','name' => 'Djibouti'),
		  array('id' => '59','name' => 'Dominica'),
		  array('id' => '60','name' => 'Denmark'),
		  array('id' => '61','name' => 'Dominican Republic'),
		  array('id' => '62','name' => 'Algeria'),
		  array('id' => '63','name' => 'Ecuador'),
		  array('id' => '64','name' => 'Egypt'),
		  array('id' => '65','name' => 'Eritrea'),
		  array('id' => '66','name' => 'Western Sahara'),
		  array('id' => '67','name' => 'Spain'),
		  array('id' => '68','name' => 'Estonia'),
		  array('id' => '69','name' => 'Ethiopia'),
		  array('id' => '70','name' => 'Finland'),
		  array('id' => '71','name' => 'Fiji Islands'),
		  array('id' => '72','name' => 'Falkland Islands'),
		  array('id' => '73','name' => 'France'),
		  array('id' => '74','name' => 'Faroe Islands'),
		  array('id' => '75','name' => 'Micronesia, Federated States o'),
		  array('id' => '76','name' => 'Gabon'),
		  array('id' => '77','name' => 'United Kingdom'),
		  array('id' => '78','name' => 'Georgia'),
		  array('id' => '79','name' => 'Ghana'),
		  array('id' => '80','name' => 'Gibraltar'),
		  array('id' => '81','name' => 'Guinea'),
		  array('id' => '82','name' => 'Guadeloupe'),
		  array('id' => '83','name' => 'Gambia'),
		  array('id' => '84','name' => 'Guinea-Bissau'),
		  array('id' => '85','name' => 'Equatorial Guinea'),
		  array('id' => '86','name' => 'Greece'),
		  array('id' => '87','name' => 'Grenada'),
		  array('id' => '88','name' => 'Greenland'),
		  array('id' => '89','name' => 'Guatemala'),
		  array('id' => '90','name' => 'French Guiana'),
		  array('id' => '91','name' => 'Guam'),
		  array('id' => '92','name' => 'Guyana'),
		  array('id' => '93','name' => 'Hong Kong'),
		  array('id' => '94','name' => 'Heard Island and McDonald Isla'),
		  array('id' => '95','name' => 'Honduras'),
		  array('id' => '96','name' => 'Croatia'),
		  array('id' => '97','name' => 'Haiti'),
		  array('id' => '98','name' => 'Hungary'),
		  array('id' => '99','name' => 'Indonesia'),
		  array('id' => '100','name' => 'India'),
		  array('id' => '101','name' => 'British Indian Ocean Territory'),
		  array('id' => '102','name' => 'Ireland'),
		  array('id' => '103','name' => 'Iran'),
		  array('id' => '104','name' => 'Iraq'),
		  array('id' => '105','name' => 'Iceland'),
		  array('id' => '106','name' => 'Israel'),
		  array('id' => '107','name' => 'Italy'),
		  array('id' => '108','name' => 'Jamaica'),
		  array('id' => '109','name' => 'Jordan'),
		  array('id' => '110','name' => 'Japan'),
		  array('id' => '111','name' => 'Kazakstan'),
		  array('id' => '112','name' => 'Kenya'),
		  array('id' => '113','name' => 'Kyrgyzstan'),
		  array('id' => '114','name' => 'Cambodia'),
		  array('id' => '115','name' => 'Kiribati'),
		  array('id' => '116','name' => 'Saint Kitts and Nevis'),
		  array('id' => '117','name' => 'South Korea'),
		  array('id' => '118','name' => 'Kuwait'),
		  array('id' => '119','name' => 'Laos'),
		  array('id' => '120','name' => 'Lebanon'),
		  array('id' => '121','name' => 'Liberia'),
		  array('id' => '122','name' => 'Libyan Arab Jamahiriya'),
		  array('id' => '123','name' => 'Saint Lucia'),
		  array('id' => '124','name' => 'Liechtenstein'),
		  array('id' => '125','name' => 'Sri Lanka'),
		  array('id' => '126','name' => 'Lesotho'),
		  array('id' => '127','name' => 'Lithuania'),
		  array('id' => '128','name' => 'Luxembourg'),
		  array('id' => '129','name' => 'Latvia'),
		  array('id' => '130','name' => 'Macao'),
		  array('id' => '131','name' => 'Morocco'),
		  array('id' => '132','name' => 'Monaco'),
		  array('id' => '133','name' => 'Moldova'),
		  array('id' => '134','name' => 'Madagascar'),
		  array('id' => '135','name' => 'Maldives'),
		  array('id' => '136','name' => 'Mexico'),
		  array('id' => '137','name' => 'Marshall Islands'),
		  array('id' => '138','name' => 'Macedonia'),
		  array('id' => '139','name' => 'Mali'),
		  array('id' => '140','name' => 'Malta'),
		  array('id' => '141','name' => 'Myanmar'),
		  array('id' => '142','name' => 'Mongolia'),
		  array('id' => '143','name' => 'Northern Mariana Islands'),
		  array('id' => '144','name' => 'Mozambique'),
		  array('id' => '145','name' => 'Mauritania'),
		  array('id' => '146','name' => 'Montserrat'),
		  array('id' => '147','name' => 'Martinique'),
		  array('id' => '148','name' => 'Mauritius'),
		  array('id' => '149','name' => 'Malawi'),
		  array('id' => '150','name' => 'Malaysia'),
		  array('id' => '151','name' => 'Mayotte'),
		  array('id' => '152','name' => 'Namibia'),
		  array('id' => '153','name' => 'New Caledonia'),
		  array('id' => '154','name' => 'Niger'),
		  array('id' => '155','name' => 'Norfolk Island'),
		  array('id' => '156','name' => 'Nigeria'),
		  array('id' => '157','name' => 'Nicaragua'),
		  array('id' => '158','name' => 'Niue'),
		  array('id' => '159','name' => 'Netherlands'),
		  array('id' => '160','name' => 'Norway'),
		  array('id' => '161','name' => 'Nepal'),
		  array('id' => '162','name' => 'Nauru'),
		  array('id' => '163','name' => 'New Zealand'),
		  array('id' => '164','name' => 'Oman'),
		  array('id' => '165','name' => 'Pakistan'),
		  array('id' => '166','name' => 'Panama'),
		  array('id' => '167','name' => 'Pitcairn'),
		  array('id' => '168','name' => 'Peru'),
		  array('id' => '169','name' => 'Philippines'),
		  array('id' => '170','name' => 'Palau'),
		  array('id' => '171','name' => 'Papua New Guinea'),
		  array('id' => '172','name' => 'Poland'),
		  array('id' => '173','name' => 'Puerto Rico'),
		  array('id' => '174','name' => 'North Korea'),
		  array('id' => '175','name' => 'Portugal'),
		  array('id' => '176','name' => 'Paraguay'),
		  array('id' => '177','name' => 'Palestine'),
		  array('id' => '178','name' => 'French Polynesia'),
		  array('id' => '179','name' => 'Qatar'),
		  array('id' => '180','name' => 'RÃ©union'),
		  array('id' => '181','name' => 'Romania'),
		  array('id' => '182','name' => 'Russian Federation'),
		  array('id' => '183','name' => 'Rwanda'),
		  array('id' => '184','name' => 'Saudi Arabia'),
		  array('id' => '185','name' => 'Sudan'),
		  array('id' => '186','name' => 'Senegal'),
		  array('id' => '187','name' => 'Singapore'),
		  array('id' => '188','name' => 'South Georgia and the South Sa'),
		  array('id' => '189','name' => 'Saint Helena'),
		  array('id' => '190','name' => 'Svalbard and Jan Mayen'),
		  array('id' => '191','name' => 'Solomon Islands'),
		  array('id' => '192','name' => 'Sierra Leone'),
		  array('id' => '193','name' => 'El Salvador'),
		  array('id' => '194','name' => 'San Marino'),
		  array('id' => '195','name' => 'Somalia'),
		  array('id' => '196','name' => 'Saint Pierre and Miquelon'),
		  array('id' => '197','name' => 'Sao Tome and Principe'),
		  array('id' => '198','name' => 'Suriname'),
		  array('id' => '199','name' => 'Slovakia'),
		  array('id' => '200','name' => 'Slovenia'),
		  array('id' => '201','name' => 'Sweden'),
		  array('id' => '202','name' => 'Swaziland'),
		  array('id' => '203','name' => 'Seychelles'),
		  array('id' => '204','name' => 'Syria'),
		  array('id' => '205','name' => 'Turks and Caicos Islands'),
		  array('id' => '206','name' => 'Chad'),
		  array('id' => '207','name' => 'Togo'),
		  array('id' => '208','name' => 'Thailand'),
		  array('id' => '209','name' => 'Tajikistan'),
		  array('id' => '210','name' => 'Tokelau'),
		  array('id' => '211','name' => 'Turkmenistan'),
		  array('id' => '212','name' => 'East Timor'),
		  array('id' => '213','name' => 'Tonga'),
		  array('id' => '214','name' => 'Trinidad and Tobago'),
		  array('id' => '215','name' => 'Tunisia'),
		  array('id' => '216','name' => 'Turkey'),
		  array('id' => '217','name' => 'Tuvalu'),
		  array('id' => '218','name' => 'Taiwan'),
		  array('id' => '219','name' => 'Tanzania'),
		  array('id' => '220','name' => 'Uganda'),
		  array('id' => '221','name' => 'Ukraine'),
		  array('id' => '222','name' => 'United States Minor Outlying I'),
		  array('id' => '223','name' => 'Uruguay'),
		  array('id' => '224','name' => 'United States'),
		  array('id' => '225','name' => 'Uzbekistan'),
		  array('id' => '226','name' => 'Holy See (Vatican City State)'),
		  array('id' => '227','name' => 'Saint Vincent and the Grenadin'),
		  array('id' => '228','name' => 'Venezuela'),
		  array('id' => '229','name' => 'Virgin Islands, British'),
		  array('id' => '230','name' => 'Virgin Islands, U.S.'),
		  array('id' => '231','name' => 'Vietnam'),
		  array('id' => '232','name' => 'Vanuatu'),
		  array('id' => '233','name' => 'Wallis and Futuna'),
		  array('id' => '234','name' => 'Samoa'),
		  array('id' => '235','name' => 'Yemen'),
		  array('id' => '236','name' => 'Yugoslavia'),
		  array('id' => '237','name' => 'South Africa'),
		  array('id' => '238','name' => 'Zambia'),
		  array('id' => '239','name' => 'Zimbabwe')
		);
		
		DB::table('countries')->insert($countries);
	}
}
