<?php

use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder {
	
	/**
	* Run the database seeds.
	*
	* @return void
	*/
	public function run() {
		
		DB::table('states')->delete();
		
		$states = array(
		  array('id' => '240','name' => 'â€“','country_id' => '1'),
		  array('id' => '241','name' => 'Balkh','country_id' => '2'),
		  array('id' => '242','name' => 'Herat','country_id' => '2'),
		  array('id' => '243','name' => 'Kabol','country_id' => '2'),
		  array('id' => '244','name' => 'Qandahar','country_id' => '2'),
		  array('id' => '245','name' => 'Benguela','country_id' => '3'),
		  array('id' => '246','name' => 'Huambo','country_id' => '3'),
		  array('id' => '247','name' => 'Luanda','country_id' => '3'),
		  array('id' => '248','name' => 'Namibe','country_id' => '3'),
		  array('id' => '249','name' => 'â€“','country_id' => '4'),
		  array('id' => '250','name' => 'Tirana','country_id' => '5'),
		  array('id' => '251','name' => 'Andorra la Vella','country_id' => '6'),
		  array('id' => '252','name' => 'CuraÃ§ao','country_id' => '7'),
		  array('id' => '253','name' => 'Abu Dhabi','country_id' => '8'),
		  array('id' => '254','name' => 'Ajman','country_id' => '8'),
		  array('id' => '255','name' => 'Dubai','country_id' => '8'),
		  array('id' => '256','name' => 'Sharja','country_id' => '8'),
		  array('id' => '257','name' => 'Buenos Aires','country_id' => '9'),
		  array('id' => '258','name' => 'Catamarca','country_id' => '9'),
		  array('id' => '259','name' => 'CÃ³rdoba','country_id' => '9'),
		  array('id' => '260','name' => 'Chaco','country_id' => '9'),
		  array('id' => '261','name' => 'Chubut','country_id' => '9'),
		  array('id' => '262','name' => 'Corrientes','country_id' => '9'),
		  array('id' => '263','name' => 'Distrito Federal','country_id' => '9'),
		  array('id' => '264','name' => 'Entre Rios','country_id' => '9'),
		  array('id' => '265','name' => 'Formosa','country_id' => '9'),
		  array('id' => '266','name' => 'Jujuy','country_id' => '9'),
		  array('id' => '267','name' => 'La Rioja','country_id' => '9'),
		  array('id' => '268','name' => 'Mendoza','country_id' => '9'),
		  array('id' => '269','name' => 'Misiones','country_id' => '9'),
		  array('id' => '270','name' => 'NeuquÃ©n','country_id' => '9'),
		  array('id' => '271','name' => 'Salta','country_id' => '9'),
		  array('id' => '272','name' => 'San Juan','country_id' => '9'),
		  array('id' => '273','name' => 'San Luis','country_id' => '9'),
		  array('id' => '274','name' => 'Santa FÃ©','country_id' => '9'),
		  array('id' => '275','name' => 'Santiago del Estero','country_id' => '9'),
		  array('id' => '276','name' => 'TucumÃ¡n','country_id' => '9'),
		  array('id' => '277','name' => 'Lori','country_id' => '10'),
		  array('id' => '278','name' => 'Yerevan','country_id' => '10'),
		  array('id' => '279','name' => 'Å irak','country_id' => '10'),
		  array('id' => '280','name' => 'Tutuila','country_id' => '11'),
		  array('id' => '281','name' => 'St John','country_id' => '14'),
		  array('id' => '282','name' => 'Capital Region','country_id' => '15'),
		  array('id' => '283','name' => 'New South Wales','country_id' => '15'),
		  array('id' => '284','name' => 'Queensland','country_id' => '15'),
		  array('id' => '285','name' => 'South Australia','country_id' => '15'),
		  array('id' => '286','name' => 'Tasmania','country_id' => '15'),
		  array('id' => '287','name' => 'Victoria','country_id' => '15'),
		  array('id' => '288','name' => 'West Australia','country_id' => '15'),
		  array('id' => '289','name' => 'KÃ¤rnten','country_id' => '16'),
		  array('id' => '290','name' => 'North Austria','country_id' => '16'),
		  array('id' => '291','name' => 'Salzburg','country_id' => '16'),
		  array('id' => '292','name' => 'Steiermark','country_id' => '16'),
		  array('id' => '293','name' => 'Tiroli','country_id' => '16'),
		  array('id' => '294','name' => 'Wien','country_id' => '16'),
		  array('id' => '295','name' => 'Baki','country_id' => '17'),
		  array('id' => '296','name' => 'GÃ¤ncÃ¤','country_id' => '17'),
		  array('id' => '297','name' => 'MingÃ¤Ã§evir','country_id' => '17'),
		  array('id' => '298','name' => 'Sumqayit','country_id' => '17'),
		  array('id' => '299','name' => 'Bujumbura','country_id' => '18'),
		  array('id' => '300','name' => 'Antwerpen','country_id' => '19'),
		  array('id' => '301','name' => 'Bryssel','country_id' => '19'),
		  array('id' => '302','name' => 'East Flanderi','country_id' => '19'),
		  array('id' => '303','name' => 'Hainaut','country_id' => '19'),
		  array('id' => '304','name' => 'LiÃ¨ge','country_id' => '19'),
		  array('id' => '305','name' => 'Namur','country_id' => '19'),
		  array('id' => '306','name' => 'West Flanderi','country_id' => '19'),
		  array('id' => '307','name' => 'Atacora','country_id' => '20'),
		  array('id' => '308','name' => 'Atlantique','country_id' => '20'),
		  array('id' => '309','name' => 'Borgou','country_id' => '20'),
		  array('id' => '310','name' => 'OuÃ©mÃ©','country_id' => '20'),
		  array('id' => '311','name' => 'BoulkiemdÃ©','country_id' => '21'),
		  array('id' => '312','name' => 'Houet','country_id' => '21'),
		  array('id' => '313','name' => 'Kadiogo','country_id' => '21'),
		  array('id' => '314','name' => 'Barisal','country_id' => '22'),
		  array('id' => '315','name' => 'Chittagong','country_id' => '22'),
		  array('id' => '316','name' => 'Dhaka','country_id' => '22'),
		  array('id' => '317','name' => 'Khulna','country_id' => '22'),
		  array('id' => '318','name' => 'Rajshahi','country_id' => '22'),
		  array('id' => '319','name' => 'Sylhet','country_id' => '22'),
		  array('id' => '320','name' => 'Burgas','country_id' => '23'),
		  array('id' => '321','name' => 'Grad Sofija','country_id' => '23'),
		  array('id' => '322','name' => 'Haskovo','country_id' => '23'),
		  array('id' => '323','name' => 'Lovec','country_id' => '23'),
		  array('id' => '324','name' => 'Plovdiv','country_id' => '23'),
		  array('id' => '325','name' => 'Ruse','country_id' => '23'),
		  array('id' => '326','name' => 'Varna','country_id' => '23'),
		  array('id' => '327','name' => 'al-Manama','country_id' => '24'),
		  array('id' => '328','name' => 'New Providence','country_id' => '25'),
		  array('id' => '329','name' => 'Federaatio','country_id' => '26'),
		  array('id' => '330','name' => 'Republika Srpska','country_id' => '26'),
		  array('id' => '331','name' => 'Brest','country_id' => '27'),
		  array('id' => '332','name' => 'Gomel','country_id' => '27'),
		  array('id' => '333','name' => 'Grodno','country_id' => '27'),
		  array('id' => '334','name' => 'Horad Minsk','country_id' => '27'),
		  array('id' => '335','name' => 'Minsk','country_id' => '27'),
		  array('id' => '336','name' => 'Mogiljov','country_id' => '27'),
		  array('id' => '337','name' => 'Vitebsk','country_id' => '27'),
		  array('id' => '338','name' => 'Belize City','country_id' => '28'),
		  array('id' => '339','name' => 'Cayo','country_id' => '28'),
		  array('id' => '340','name' => 'Hamilton','country_id' => '29'),
		  array('id' => '341','name' => 'Saint GeorgeÂ´s','country_id' => '29'),
		  array('id' => '342','name' => 'Chuquisaca','country_id' => '30'),
		  array('id' => '343','name' => 'Cochabamba','country_id' => '30'),
		  array('id' => '344','name' => 'La Paz','country_id' => '30'),
		  array('id' => '345','name' => 'Oruro','country_id' => '30'),
		  array('id' => '346','name' => 'PotosÃ­','country_id' => '30'),
		  array('id' => '347','name' => 'Santa Cruz','country_id' => '30'),
		  array('id' => '348','name' => 'Tarija','country_id' => '30'),
		  array('id' => '349','name' => 'Acre','country_id' => '31'),
		  array('id' => '350','name' => 'Alagoas','country_id' => '31'),
		  array('id' => '351','name' => 'AmapÃ¡','country_id' => '31'),
		  array('id' => '352','name' => 'Amazonas','country_id' => '31'),
		  array('id' => '353','name' => 'Bahia','country_id' => '31'),
		  array('id' => '354','name' => 'CearÃ¡','country_id' => '31'),
		  array('id' => '355','name' => 'Distrito Federal','country_id' => '31'),
		  array('id' => '356','name' => 'EspÃ­rito Santo','country_id' => '31'),
		  array('id' => '357','name' => 'GoiÃ¡s','country_id' => '31'),
		  array('id' => '358','name' => 'MaranhÃ£o','country_id' => '31'),
		  array('id' => '359','name' => 'Mato Grosso','country_id' => '31'),
		  array('id' => '360','name' => 'Mato Grosso do Sul','country_id' => '31'),
		  array('id' => '361','name' => 'Minas Gerais','country_id' => '31'),
		  array('id' => '362','name' => 'ParaÃ­ba','country_id' => '31'),
		  array('id' => '363','name' => 'ParanÃ¡','country_id' => '31'),
		  array('id' => '364','name' => 'ParÃ¡','country_id' => '31'),
		  array('id' => '365','name' => 'Pernambuco','country_id' => '31'),
		  array('id' => '366','name' => 'PiauÃ­','country_id' => '31'),
		  array('id' => '367','name' => 'Rio de Janeiro','country_id' => '31'),
		  array('id' => '368','name' => 'Rio Grande do Norte','country_id' => '31'),
		  array('id' => '369','name' => 'Rio Grande do Sul','country_id' => '31'),
		  array('id' => '370','name' => 'RondÃ´nia','country_id' => '31'),
		  array('id' => '371','name' => 'Roraima','country_id' => '31'),
		  array('id' => '372','name' => 'Santa Catarina','country_id' => '31'),
		  array('id' => '373','name' => 'SÃ£o Paulo','country_id' => '31'),
		  array('id' => '374','name' => 'Sergipe','country_id' => '31'),
		  array('id' => '375','name' => 'Tocantins','country_id' => '31'),
		  array('id' => '376','name' => 'St Michael','country_id' => '32'),
		  array('id' => '377','name' => 'Brunei and Muara','country_id' => '33'),
		  array('id' => '378','name' => 'Thimphu','country_id' => '34'),
		  array('id' => '379','name' => 'Francistown','country_id' => '36'),
		  array('id' => '380','name' => 'Gaborone','country_id' => '36'),
		  array('id' => '381','name' => 'Bangui','country_id' => '37'),
		  array('id' => '382','name' => 'Alberta','country_id' => '38'),
		  array('id' => '383','name' => 'British Colombia','country_id' => '38'),
		  array('id' => '384','name' => 'Manitoba','country_id' => '38'),
		  array('id' => '385','name' => 'Newfoundland','country_id' => '38'),
		  array('id' => '386','name' => 'Nova Scotia','country_id' => '38'),
		  array('id' => '387','name' => 'Ontario','country_id' => '38'),
		  array('id' => '388','name' => 'QuÃ©bec','country_id' => '38'),
		  array('id' => '389','name' => 'Saskatchewan','country_id' => '38'),
		  array('id' => '390','name' => 'Home Island','country_id' => '39'),
		  array('id' => '391','name' => 'West Island','country_id' => '39'),
		  array('id' => '392','name' => 'Basel-Stadt','country_id' => '40'),
		  array('id' => '393','name' => 'Bern','country_id' => '40'),
		  array('id' => '394','name' => 'Geneve','country_id' => '40'),
		  array('id' => '395','name' => 'Vaud','country_id' => '40'),
		  array('id' => '396','name' => 'ZÃ¼rich','country_id' => '40'),
		  array('id' => '397','name' => 'Antofagasta','country_id' => '41'),
		  array('id' => '398','name' => 'Atacama','country_id' => '41'),
		  array('id' => '399','name' => 'BÃ­obÃ­o','country_id' => '41'),
		  array('id' => '400','name' => 'Coquimbo','country_id' => '41'),
		  array('id' => '401','name' => 'La AraucanÃ­a','country_id' => '41'),
		  array('id' => '402','name' => 'Los Lagos','country_id' => '41'),
		  array('id' => '403','name' => 'Magallanes','country_id' => '41'),
		  array('id' => '404','name' => 'Maule','country_id' => '41'),
		  array('id' => '405','name' => 'OÂ´Higgins','country_id' => '41'),
		  array('id' => '406','name' => 'Santiago','country_id' => '41'),
		  array('id' => '407','name' => 'TarapacÃ¡','country_id' => '41'),
		  array('id' => '408','name' => 'ValparaÃ­so','country_id' => '41'),
		  array('id' => '409','name' => 'Anhui','country_id' => '42'),
		  array('id' => '410','name' => 'Chongqing','country_id' => '42'),
		  array('id' => '411','name' => 'Fujian','country_id' => '42'),
		  array('id' => '412','name' => 'Gansu','country_id' => '42'),
		  array('id' => '413','name' => 'Guangdong','country_id' => '42'),
		  array('id' => '414','name' => 'Guangxi','country_id' => '42'),
		  array('id' => '415','name' => 'Guizhou','country_id' => '42'),
		  array('id' => '416','name' => 'Hainan','country_id' => '42'),
		  array('id' => '417','name' => 'Hebei','country_id' => '42'),
		  array('id' => '418','name' => 'Heilongjiang','country_id' => '42'),
		  array('id' => '419','name' => 'Henan','country_id' => '42'),
		  array('id' => '420','name' => 'Hubei','country_id' => '42'),
		  array('id' => '421','name' => 'Hunan','country_id' => '42'),
		  array('id' => '422','name' => 'Inner Mongolia','country_id' => '42'),
		  array('id' => '423','name' => 'Jiangsu','country_id' => '42'),
		  array('id' => '424','name' => 'Jiangxi','country_id' => '42'),
		  array('id' => '425','name' => 'Jilin','country_id' => '42'),
		  array('id' => '426','name' => 'Liaoning','country_id' => '42'),
		  array('id' => '427','name' => 'Ningxia','country_id' => '42'),
		  array('id' => '428','name' => 'Peking','country_id' => '42'),
		  array('id' => '429','name' => 'Qinghai','country_id' => '42'),
		  array('id' => '430','name' => 'Shaanxi','country_id' => '42'),
		  array('id' => '431','name' => 'Shandong','country_id' => '42'),
		  array('id' => '432','name' => 'Shanghai','country_id' => '42'),
		  array('id' => '433','name' => 'Shanxi','country_id' => '42'),
		  array('id' => '434','name' => 'Sichuan','country_id' => '42'),
		  array('id' => '435','name' => 'Tianjin','country_id' => '42'),
		  array('id' => '436','name' => 'Tibet','country_id' => '42'),
		  array('id' => '437','name' => 'Xinxiang','country_id' => '42'),
		  array('id' => '438','name' => 'Yunnan','country_id' => '42'),
		  array('id' => '439','name' => 'Zhejiang','country_id' => '42'),
		  array('id' => '440','name' => 'Abidjan','country_id' => '43'),
		  array('id' => '441','name' => 'BouakÃ©','country_id' => '43'),
		  array('id' => '442','name' => 'Daloa','country_id' => '43'),
		  array('id' => '443','name' => 'Korhogo','country_id' => '43'),
		  array('id' => '444','name' => 'Yamoussoukro','country_id' => '43'),
		  array('id' => '445','name' => 'Centre','country_id' => '44'),
		  array('id' => '446','name' => 'ExtrÃªme-Nord','country_id' => '44'),
		  array('id' => '447','name' => 'Littoral','country_id' => '44'),
		  array('id' => '448','name' => 'Nord','country_id' => '44'),
		  array('id' => '449','name' => 'Nord-Ouest','country_id' => '44'),
		  array('id' => '450','name' => 'Ouest','country_id' => '44'),
		  
		  array('id' => '451','name' => 'Bandundu','country_id' => '45'),
		  array('id' => '452','name' => 'Bas-ZaÃ¯re','country_id' => '45'),
		  array('id' => '453','name' => 'East Kasai','country_id' => '45'),
		  array('id' => '454','name' => 'Equateur','country_id' => '45'),
		  array('id' => '455','name' => 'Haute-ZaÃ¯re','country_id' => '45'),
		  array('id' => '456','name' => 'Kinshasa','country_id' => '45'),
		  array('id' => '457','name' => 'North Kivu','country_id' => '45'),
		  array('id' => '458','name' => 'Shaba','country_id' => '45'),
		  array('id' => '459','name' => 'South Kivu','country_id' => '45'),
		  array('id' => '460','name' => 'West Kasai','country_id' => '45'),
		  
		  array('id' => '461','name' => 'Brazzaville','country_id' => '46'),
		  array('id' => '462','name' => 'Kouilou','country_id' => '46'),
		  array('id' => '463','name' => 'Rarotonga','country_id' => '47'),
		  array('id' => '464','name' => 'Antioquia','country_id' => '48'),
		  array('id' => '465','name' => 'AtlÃ¡ntico','country_id' => '48'),
		  array('id' => '466','name' => 'BolÃ­var','country_id' => '48'),
		  array('id' => '467','name' => 'BoyacÃ¡','country_id' => '48'),
		  array('id' => '468','name' => 'Caldas','country_id' => '48'),
		  array('id' => '469','name' => 'CaquetÃ¡','country_id' => '48'),
		  array('id' => '470','name' => 'Cauca','country_id' => '48'),
		  array('id' => '471','name' => 'CÃ³rdoba','country_id' => '48'),
		  array('id' => '472','name' => 'Cesar','country_id' => '48'),
		  array('id' => '473','name' => 'Cundinamarca','country_id' => '48'),
		  array('id' => '474','name' => 'Huila','country_id' => '48'),
		  array('id' => '475','name' => 'La Guajira','country_id' => '48'),
		  array('id' => '476','name' => 'Magdalena','country_id' => '48'),
		  array('id' => '477','name' => 'Meta','country_id' => '48'),
		  array('id' => '478','name' => 'NariÃ±o','country_id' => '48'),
		  array('id' => '479','name' => 'Norte de Santander','country_id' => '48'),
		  array('id' => '480','name' => 'QuindÃ­o','country_id' => '48'),
		  array('id' => '481','name' => 'Risaralda','country_id' => '48'),
		  array('id' => '482','name' => 'SantafÃ© de BogotÃ¡','country_id' => '48'),
		  array('id' => '483','name' => 'Santander','country_id' => '48'),
		  array('id' => '484','name' => 'Sucre','country_id' => '48'),
		  array('id' => '485','name' => 'Tolima','country_id' => '48'),
		  array('id' => '486','name' => 'Valle','country_id' => '48'),
		  array('id' => '487','name' => 'Njazidja','country_id' => '49'),
		  array('id' => '488','name' => 'SÃ£o Tiago','country_id' => '50'),
		  array('id' => '489','name' => 'San JosÃ©','country_id' => '51'),
		  array('id' => '490','name' => 'CamagÃ¼ey','country_id' => '52'),
		  array('id' => '491','name' => 'Ciego de Ãvila','country_id' => '52'),
		  array('id' => '492','name' => 'Cienfuegos','country_id' => '52'),
		  array('id' => '493','name' => 'Granma','country_id' => '52'),
		  array('id' => '494','name' => 'GuantÃ¡namo','country_id' => '52'),
		  array('id' => '495','name' => 'HolguÃ­n','country_id' => '52'),
		  array('id' => '496','name' => 'La Habana','country_id' => '52'),
		  array('id' => '497','name' => 'Las Tunas','country_id' => '52'),
		  array('id' => '498','name' => 'Matanzas','country_id' => '52'),
		  array('id' => '499','name' => 'Pinar del RÃ­o','country_id' => '52'),
		  array('id' => '500','name' => 'Sancti-SpÃ­ritus','country_id' => '52'),
		  array('id' => '501','name' => 'Santiago de Cuba','country_id' => '52'),
		  array('id' => '502','name' => 'Villa Clara','country_id' => '52'),
		  array('id' => '503','name' => 'â€“','country_id' => '53'),
		  array('id' => '504','name' => 'Grand Cayman','country_id' => '54'),
		  array('id' => '505','name' => 'Limassol','country_id' => '55'),
		  array('id' => '506','name' => 'Nicosia','country_id' => '55'),
		  array('id' => '507','name' => 'HlavnÃ­ mesto Praha','country_id' => '56'),
		  array('id' => '508','name' => 'JiznÃ­ Cechy','country_id' => '56'),
		  array('id' => '509','name' => 'JiznÃ­ Morava','country_id' => '56'),
		  array('id' => '510','name' => 'SevernÃ­ Cechy','country_id' => '56'),
		  array('id' => '511','name' => 'SevernÃ­ Morava','country_id' => '56'),
		  array('id' => '512','name' => 'VÃ½chodnÃ­ Cechy','country_id' => '56'),
		  array('id' => '513','name' => 'ZapadnÃ­ Cechy','country_id' => '56'),
		  array('id' => '514','name' => 'Anhalt Sachsen','country_id' => '57'),
		  array('id' => '515','name' => 'Baden-WÃ¼rttemberg','country_id' => '57'),
		  array('id' => '516','name' => 'Baijeri','country_id' => '57'),
		  array('id' => '517','name' => 'Berliini','country_id' => '57'),
		  array('id' => '518','name' => 'Brandenburg','country_id' => '57'),
		  array('id' => '519','name' => 'Bremen','country_id' => '57'),
		  array('id' => '520','name' => 'Hamburg','country_id' => '57'),
		  array('id' => '521','name' => 'Hessen','country_id' => '57'),
		  array('id' => '522','name' => 'Mecklenburg-Vorpomme','country_id' => '57'),
		  array('id' => '523','name' => 'Niedersachsen','country_id' => '57'),
		  array('id' => '524','name' => 'Nordrhein-Westfalen','country_id' => '57'),
		  array('id' => '525','name' => 'Rheinland-Pfalz','country_id' => '57'),
		  array('id' => '526','name' => 'Saarland','country_id' => '57'),
		  array('id' => '527','name' => 'Saksi','country_id' => '57'),
		  array('id' => '528','name' => 'Schleswig-Holstein','country_id' => '57'),
		  array('id' => '529','name' => 'ThÃ¼ringen','country_id' => '57'),
		  array('id' => '530','name' => 'Djibouti','country_id' => '58'),
		  array('id' => '531','name' => 'St George','country_id' => '59'),
		  array('id' => '532','name' => 'Ã…rhus','country_id' => '60'),
		  array('id' => '533','name' => 'Frederiksberg','country_id' => '60'),
		  array('id' => '534','name' => 'Fyn','country_id' => '60'),
		  array('id' => '535','name' => 'KÃ¸benhavn','country_id' => '60'),
		  array('id' => '536','name' => 'Nordjylland','country_id' => '60'),
		  array('id' => '537','name' => 'Distrito Nacional','country_id' => '61'),
		  array('id' => '538','name' => 'Duarte','country_id' => '61'),
		  array('id' => '539','name' => 'La Romana','country_id' => '61'),
		  array('id' => '540','name' => 'Puerto Plata','country_id' => '61'),
		  array('id' => '541','name' => 'San Pedro de MacorÃ­','country_id' => '61'),
		  array('id' => '542','name' => 'Santiago','country_id' => '61'),
		  array('id' => '543','name' => 'Alger','country_id' => '62'),
		  array('id' => '544','name' => 'Annaba','country_id' => '62'),
		  array('id' => '545','name' => 'Batna','country_id' => '62'),
		  array('id' => '546','name' => 'BÃ©char','country_id' => '62'),
		  array('id' => '547','name' => 'BÃ©jaÃ¯a','country_id' => '62'),
		  array('id' => '548','name' => 'Biskra','country_id' => '62'),
		  array('id' => '549','name' => 'Blida','country_id' => '62'),
		  array('id' => '550','name' => 'Chlef','country_id' => '62'),
		  array('id' => '551','name' => 'Constantine','country_id' => '62'),
		  array('id' => '552','name' => 'GhardaÃ¯a','country_id' => '62'),
		  array('id' => '553','name' => 'Mostaganem','country_id' => '62'),
		  array('id' => '554','name' => 'Oran','country_id' => '62'),
		  array('id' => '555','name' => 'SÃ©tif','country_id' => '62'),
		  array('id' => '556','name' => 'Sidi Bel AbbÃ¨s','country_id' => '62'),
		  array('id' => '557','name' => 'Skikda','country_id' => '62'),
		  array('id' => '558','name' => 'TÃ©bessa','country_id' => '62'),
		  array('id' => '559','name' => 'Tiaret','country_id' => '62'),
		  array('id' => '560','name' => 'Tlemcen','country_id' => '62'),
		  array('id' => '561','name' => 'Azuay','country_id' => '63'),
		  array('id' => '562','name' => 'Chimborazo','country_id' => '63'),
		  array('id' => '563','name' => 'El Oro','country_id' => '63'),
		  array('id' => '564','name' => 'Esmeraldas','country_id' => '63'),
		  array('id' => '565','name' => 'Guayas','country_id' => '63'),
		  array('id' => '566','name' => 'Imbabura','country_id' => '63'),
		  array('id' => '567','name' => 'Loja','country_id' => '63'),
		  array('id' => '568','name' => 'Los RÃ­os','country_id' => '63'),
		  array('id' => '569','name' => 'ManabÃ­','country_id' => '63'),
		  array('id' => '570','name' => 'Pichincha','country_id' => '63'),
		  array('id' => '571','name' => 'Tungurahua','country_id' => '63'),
		  array('id' => '572','name' => 'al-Buhayra','country_id' => '64'),
		  array('id' => '573','name' => 'al-Daqahliya','country_id' => '64'),
		  array('id' => '574','name' => 'al-Faiyum','country_id' => '64'),
		  array('id' => '575','name' => 'al-Gharbiya','country_id' => '64'),
		  array('id' => '576','name' => 'al-Minufiya','country_id' => '64'),
		  array('id' => '577','name' => 'al-Minya','country_id' => '64'),
		  array('id' => '578','name' => 'al-Qalyubiya','country_id' => '64'),
		  array('id' => '579','name' => 'al-Sharqiya','country_id' => '64'),
		  array('id' => '580','name' => 'Aleksandria','country_id' => '64'),
		  array('id' => '581','name' => 'Assuan','country_id' => '64'),
		  array('id' => '582','name' => 'Asyut','country_id' => '64'),
		  array('id' => '583','name' => 'Bani Suwayf','country_id' => '64'),
		  array('id' => '584','name' => 'Giza','country_id' => '64'),
		  array('id' => '585','name' => 'Ismailia','country_id' => '64'),
		  array('id' => '586','name' => 'Kafr al-Shaykh','country_id' => '64'),
		  array('id' => '587','name' => 'Kairo','country_id' => '64'),
		  array('id' => '588','name' => 'Luxor','country_id' => '64'),
		  array('id' => '589','name' => 'Port Said','country_id' => '64'),
		  array('id' => '590','name' => 'Qina','country_id' => '64'),
		  array('id' => '591','name' => 'Sawhaj','country_id' => '64'),
		  array('id' => '592','name' => 'Shamal Sina','country_id' => '64'),
		  array('id' => '593','name' => 'Suez','country_id' => '64'),
		  array('id' => '594','name' => 'Maekel','country_id' => '65'),
		  array('id' => '595','name' => 'El-AaiÃºn','country_id' => '66'),
		  array('id' => '596','name' => 'Andalusia','country_id' => '67'),
		  array('id' => '597','name' => 'Aragonia','country_id' => '67'),
		  array('id' => '598','name' => 'Asturia','country_id' => '67'),
		  array('id' => '599','name' => 'Balears','country_id' => '67'),
		  array('id' => '600','name' => 'Baskimaa','country_id' => '67'),
		  array('id' => '601','name' => 'Canary Islands','country_id' => '67'),
		  array('id' => '602','name' => 'Cantabria','country_id' => '67'),
		  array('id' => '603','name' => 'Castilla and LeÃ³n','country_id' => '67'),
		  array('id' => '604','name' => 'Extremadura','country_id' => '67'),
		  array('id' => '605','name' => 'Galicia','country_id' => '67'),
		  array('id' => '606','name' => 'Kastilia-La Mancha','country_id' => '67'),
		  array('id' => '607','name' => 'Katalonia','country_id' => '67'),
		  array('id' => '608','name' => 'La Rioja','country_id' => '67'),
		  array('id' => '609','name' => 'Madrid','country_id' => '67'),
		  array('id' => '610','name' => 'Murcia','country_id' => '67'),
		  array('id' => '611','name' => 'Navarra','country_id' => '67'),
		  array('id' => '612','name' => 'Valencia','country_id' => '67'),
		  array('id' => '613','name' => 'Harjumaa','country_id' => '68'),
		  array('id' => '614','name' => 'Tartumaa','country_id' => '68'),
		  array('id' => '615','name' => 'Addis Abeba','country_id' => '69'),
		  array('id' => '616','name' => 'Amhara','country_id' => '69'),
		  array('id' => '617','name' => 'Dire Dawa','country_id' => '69'),
		  array('id' => '618','name' => 'Oromia','country_id' => '69'),
		  array('id' => '619','name' => 'Tigray','country_id' => '69'),
		  array('id' => '620','name' => 'Newmaa','country_id' => '70'),
		  array('id' => '621','name' => 'PÃ¤ijÃ¤t-HÃ¤me','country_id' => '70'),
		  array('id' => '622','name' => 'Pirkanmaa','country_id' => '70'),
		  array('id' => '623','name' => 'Pohjois-Pohjanmaa','country_id' => '70'),
		  array('id' => '624','name' => 'Varsinais-Suomi','country_id' => '70'),
		  array('id' => '625','name' => 'Central','country_id' => '71'),
		  array('id' => '626','name' => 'East Falkland','country_id' => '72'),
		  array('id' => '627','name' => 'Alsace','country_id' => '73'),
		  array('id' => '628','name' => 'Aquitaine','country_id' => '73'),
		  array('id' => '629','name' => 'Auvergne','country_id' => '73'),
		  array('id' => '630','name' => 'ÃŽle-de-France','country_id' => '73'),
		  array('id' => '631','name' => 'Basse-Normandie','country_id' => '73'),
		  array('id' => '632','name' => 'Bourgogne','country_id' => '73'),
		  array('id' => '633','name' => 'Bretagne','country_id' => '73'),
		  array('id' => '634','name' => 'Centre','country_id' => '73'),
		  array('id' => '635','name' => 'Champagne-Ardenne','country_id' => '73'),
		  array('id' => '636','name' => 'Franche-ComtÃ©','country_id' => '73'),
		  array('id' => '637','name' => 'Haute-Normandie','country_id' => '73'),
		  array('id' => '638','name' => 'Languedoc-Roussillon','country_id' => '73'),
		  array('id' => '639','name' => 'Limousin','country_id' => '73'),
		  array('id' => '640','name' => 'Lorraine','country_id' => '73'),
		  array('id' => '641','name' => 'Midi-PyrÃ©nÃ©es','country_id' => '73'),
		  array('id' => '642','name' => 'Nord-Pas-de-Calais','country_id' => '73'),
		  array('id' => '643','name' => 'Pays de la Loire','country_id' => '73'),
		  array('id' => '644','name' => 'Picardie','country_id' => '73'),
		  array('id' => '645','name' => 'Provence-Alpes-CÃ´te','country_id' => '73'),
		  array('id' => '646','name' => 'RhÃ´ne-Alpes','country_id' => '73'),
		  array('id' => '647','name' => 'Streymoyar','country_id' => '74'),
			//array('id' => '648','name' => 'Chuuk','country_id' => '0'),
			//array('id' => '649','name' => 'Pohnpei','country_id' => '0'),
		  array('id' => '650','name' => 'Estuaire','country_id' => '76'),
		  array('id' => '651','name' => 'â€“','country_id' => '77'),
		  array('id' => '652','name' => 'England','country_id' => '77'),
		  array('id' => '653','name' => 'Jersey','country_id' => '77'),
		  array('id' => '654','name' => 'North Ireland','country_id' => '77'),
		  array('id' => '655','name' => 'Scotland','country_id' => '77'),
		  array('id' => '656','name' => 'Wales','country_id' => '77'),
		  array('id' => '657','name' => 'Abhasia [Aphazeti]','country_id' => '78'),
		  array('id' => '658','name' => 'Adzaria [AtÅ¡ara]','country_id' => '78'),
		  array('id' => '659','name' => 'Imereti','country_id' => '78'),
		  array('id' => '660','name' => 'Kvemo Kartli','country_id' => '78'),
		  array('id' => '661','name' => 'Tbilisi','country_id' => '78'),
		  array('id' => '662','name' => 'Ashanti','country_id' => '79'),
		  array('id' => '663','name' => 'Greater Accra','country_id' => '79'),
		  array('id' => '664','name' => 'Northern','country_id' => '79'),
		  array('id' => '665','name' => 'Western','country_id' => '79'),
		  array('id' => '666','name' => 'â€“','country_id' => '80'),
		  array('id' => '667','name' => 'Conakry','country_id' => '81'),
		  array('id' => '668','name' => 'Basse-Terre','country_id' => '82'),
		  array('id' => '669','name' => 'Grande-Terre','country_id' => '82'),
		  array('id' => '670','name' => 'Banjul','country_id' => '83'),
		  array('id' => '671','name' => 'Kombo St Mary','country_id' => '83'),
		  array('id' => '672','name' => 'Bissau','country_id' => '84'),
		  array('id' => '673','name' => 'Bioko','country_id' => '85'),
		  array('id' => '674','name' => 'Attika','country_id' => '86'),
		  array('id' => '675','name' => 'Central Macedonia','country_id' => '86'),
		  array('id' => '676','name' => 'Crete','country_id' => '86'),
		  array('id' => '677','name' => 'Thessalia','country_id' => '86'),
		  array('id' => '678','name' => 'West Greece','country_id' => '86'),
		  array('id' => '679','name' => 'St George','country_id' => '87'),
		  array('id' => '680','name' => 'Kitaa','country_id' => '88'),
		  array('id' => '681','name' => 'Guatemala','country_id' => '89'),
		  array('id' => '682','name' => 'Quetzaltenango','country_id' => '89'),
		  array('id' => '683','name' => 'Cayenne','country_id' => '90'),
		  array('id' => '684','name' => 'â€“','country_id' => '91'),
		  array('id' => '685','name' => 'Georgetown','country_id' => '92'),
		  array('id' => '686','name' => 'Hongkong','country_id' => '93'),
		  array('id' => '687','name' => 'Kowloon and New Kowl','country_id' => '93'),
		  array('id' => '688','name' => 'AtlÃ¡ntida','country_id' => '95'),
		  array('id' => '689','name' => 'CortÃ©s','country_id' => '95'),
		  array('id' => '690','name' => 'Distrito Central','country_id' => '95'),
		  array('id' => '691','name' => 'Grad Zagreb','country_id' => '96'),
		  array('id' => '692','name' => 'Osijek-Baranja','country_id' => '96'),
		  array('id' => '693','name' => 'Primorje-Gorski Kota','country_id' => '96'),
		  array('id' => '694','name' => 'Split-Dalmatia','country_id' => '96'),
		  array('id' => '695','name' => 'Nord','country_id' => '97'),
		  array('id' => '696','name' => 'Ouest','country_id' => '97'),
		  array('id' => '697','name' => 'Baranya','country_id' => '98'),
		  array('id' => '698','name' => 'BÃ¡cs-Kiskun','country_id' => '98'),
		  array('id' => '699','name' => 'Borsod-AbaÃºj-ZemplÃ','country_id' => '98'),
		  array('id' => '700','name' => 'Budapest','country_id' => '98'),
		  array('id' => '701','name' => 'CsongrÃ¡d','country_id' => '98'),
		  array('id' => '702','name' => 'FejÃ©r','country_id' => '98'),
		  array('id' => '703','name' => 'GyÃ¶r-Moson-Sopron','country_id' => '98'),
		  array('id' => '704','name' => 'HajdÃº-Bihar','country_id' => '98'),
		  array('id' => '705','name' => 'Szabolcs-SzatmÃ¡r-Be','country_id' => '98'),
		  array('id' => '706','name' => 'Aceh','country_id' => '99'),
		  array('id' => '707','name' => 'Bali','country_id' => '99'),
		  array('id' => '708','name' => 'Bengkulu','country_id' => '99'),
		  array('id' => '709','name' => 'Central Java','country_id' => '99'),
		  array('id' => '710','name' => 'East Java','country_id' => '99'),
		  array('id' => '711','name' => 'Jakarta Raya','country_id' => '99'),
		  array('id' => '712','name' => 'Jambi','country_id' => '99'),
		  array('id' => '713','name' => 'Kalimantan Barat','country_id' => '99'),
		  array('id' => '714','name' => 'Kalimantan Selatan','country_id' => '99'),
		  array('id' => '715','name' => 'Kalimantan Tengah','country_id' => '99'),
		  array('id' => '716','name' => 'Kalimantan Timur','country_id' => '99'),
		  array('id' => '717','name' => 'Lampung','country_id' => '99'),
		  array('id' => '718','name' => 'Molukit','country_id' => '99'),
		  array('id' => '719','name' => 'Nusa Tenggara Barat','country_id' => '99'),
		  array('id' => '720','name' => 'Nusa Tenggara Timur','country_id' => '99'),
		  array('id' => '721','name' => 'Riau','country_id' => '99'),
		  array('id' => '722','name' => 'Sulawesi Selatan','country_id' => '99'),
		  array('id' => '723','name' => 'Sulawesi Tengah','country_id' => '99'),
		  array('id' => '724','name' => 'Sulawesi Tenggara','country_id' => '99'),
		  array('id' => '725','name' => 'Sulawesi Utara','country_id' => '99'),
		  array('id' => '726','name' => 'Sumatera Barat','country_id' => '99'),
		  array('id' => '727','name' => 'Sumatera Selatan','country_id' => '99'),
		  array('id' => '728','name' => 'Sumatera Utara','country_id' => '99'),
		  array('id' => '729','name' => 'West Irian','country_id' => '99'),
		  array('id' => '730','name' => 'West Java','country_id' => '99'),
		  array('id' => '731','name' => 'Yogyakarta','country_id' => '99'),
		  array('id' => '732','name' => 'Andhra Pradesh','country_id' => '100'),
		  array('id' => '733','name' => 'Assam','country_id' => '100'),
		  array('id' => '734','name' => 'Bihar','country_id' => '100'),
		  array('id' => '735','name' => 'Chandigarh','country_id' => '100'),
		  array('id' => '736','name' => 'Chhatisgarh','country_id' => '100'),
		  array('id' => '737','name' => 'Delhi','country_id' => '100'),
		  array('id' => '738','name' => 'Gujarat','country_id' => '100'),
		  array('id' => '739','name' => 'Haryana','country_id' => '100'),
		  array('id' => '740','name' => 'Jammu and Kashmir','country_id' => '100'),
		  array('id' => '741','name' => 'Jharkhand','country_id' => '100'),
		  array('id' => '742','name' => 'Karnataka','country_id' => '100'),
		  array('id' => '743','name' => 'Kerala','country_id' => '100'),
		  array('id' => '744','name' => 'Madhya Pradesh','country_id' => '100'),
		  array('id' => '745','name' => 'Maharashtra','country_id' => '100'),
		  array('id' => '746','name' => 'Manipur','country_id' => '100'),
		  array('id' => '747','name' => 'Meghalaya','country_id' => '100'),
		  array('id' => '748','name' => 'Mizoram','country_id' => '100'),
		  array('id' => '749','name' => 'Orissa','country_id' => '100'),
		  array('id' => '750','name' => 'Pondicherry','country_id' => '100'),
		  array('id' => '751','name' => 'Punjab','country_id' => '100'),
		  array('id' => '752','name' => 'Rajasthan','country_id' => '100'),
		  array('id' => '753','name' => 'Tamil Nadu','country_id' => '100'),
		  array('id' => '754','name' => 'Tripura','country_id' => '100'),
		  array('id' => '755','name' => 'Uttar Pradesh','country_id' => '100'),
		  array('id' => '756','name' => 'Uttaranchal','country_id' => '100'),
		  array('id' => '757','name' => 'West Bengal','country_id' => '100'),
		  array('id' => '758','name' => 'Leinster','country_id' => '102'),
		  array('id' => '759','name' => 'Munster','country_id' => '102'),
		  array('id' => '760','name' => 'Ardebil','country_id' => '103'),
		  array('id' => '761','name' => 'Bushehr','country_id' => '103'),
		  array('id' => '762','name' => 'Chaharmahal va Bakht','country_id' => '103'),
		  array('id' => '763','name' => 'East Azerbaidzan','country_id' => '103'),
		  array('id' => '764','name' => 'Esfahan','country_id' => '103'),
		  array('id' => '765','name' => 'Fars','country_id' => '103'),
		  array('id' => '766','name' => 'Gilan','country_id' => '103'),
		  array('id' => '767','name' => 'Golestan','country_id' => '103'),
		  array('id' => '768','name' => 'Hamadan','country_id' => '103'),
		  array('id' => '769','name' => 'Hormozgan','country_id' => '103'),
		  array('id' => '770','name' => 'Ilam','country_id' => '103'),
		  array('id' => '771','name' => 'Kerman','country_id' => '103'),
		  array('id' => '772','name' => 'Kermanshah','country_id' => '103'),
		  array('id' => '773','name' => 'Khorasan','country_id' => '103'),
		  array('id' => '774','name' => 'Khuzestan','country_id' => '103'),
		  array('id' => '775','name' => 'Kordestan','country_id' => '103'),
		  array('id' => '776','name' => 'Lorestan','country_id' => '103'),
		  array('id' => '777','name' => 'Markazi','country_id' => '103'),
		  array('id' => '778','name' => 'Mazandaran','country_id' => '103'),
		  array('id' => '779','name' => 'Qazvin','country_id' => '103'),
		  array('id' => '780','name' => 'Qom','country_id' => '103'),
		  array('id' => '781','name' => 'Semnan','country_id' => '103'),
		  array('id' => '782','name' => 'Sistan va Baluchesta','country_id' => '103'),
		  array('id' => '783','name' => 'Teheran','country_id' => '103'),
		  array('id' => '784','name' => 'West Azerbaidzan','country_id' => '103'),
		  array('id' => '785','name' => 'Yazd','country_id' => '103'),
		  array('id' => '786','name' => 'Zanjan','country_id' => '103'),
		  array('id' => '787','name' => 'al-Anbar','country_id' => '104'),
		  array('id' => '788','name' => 'al-Najaf','country_id' => '104'),
		  array('id' => '789','name' => 'al-Qadisiya','country_id' => '104'),
		  array('id' => '790','name' => 'al-Sulaymaniya','country_id' => '104'),
		  array('id' => '791','name' => 'al-Tamim','country_id' => '104'),
		  array('id' => '792','name' => 'Babil','country_id' => '104'),
		  array('id' => '793','name' => 'Baghdad','country_id' => '104'),
		  array('id' => '794','name' => 'Basra','country_id' => '104'),
		  array('id' => '795','name' => 'DhiQar','country_id' => '104'),
		  array('id' => '796','name' => 'Diyala','country_id' => '104'),
		  array('id' => '797','name' => 'Irbil','country_id' => '104'),
		  array('id' => '798','name' => 'Karbala','country_id' => '104'),
		  array('id' => '799','name' => 'Maysan','country_id' => '104'),
		  array('id' => '800','name' => 'Ninawa','country_id' => '104'),
		  array('id' => '801','name' => 'Wasit','country_id' => '104'),
		  array('id' => '802','name' => 'HÃ¶fuÃ°borgarsvÃ¦Ã°i','country_id' => '105'),
		  array('id' => '803','name' => 'Ha Darom','country_id' => '106'),
		  array('id' => '804','name' => 'Ha Merkaz','country_id' => '106'),
		  array('id' => '805','name' => 'Haifa','country_id' => '106'),
		  array('id' => '806','name' => 'Jerusalem','country_id' => '106'),
		  array('id' => '807','name' => 'Tel Aviv','country_id' => '106'),
		  array('id' => '808','name' => 'Abruzzit','country_id' => '107'),
		  array('id' => '809','name' => 'Apulia','country_id' => '107'),
		  array('id' => '810','name' => 'Calabria','country_id' => '107'),
		  array('id' => '811','name' => 'Campania','country_id' => '107'),
		  array('id' => '812','name' => 'Emilia-Romagna','country_id' => '107'),
		  array('id' => '813','name' => 'Friuli-Venezia Giuli','country_id' => '107'),
		  array('id' => '814','name' => 'Latium','country_id' => '107'),
		  array('id' => '815','name' => 'Liguria','country_id' => '107'),
		  array('id' => '816','name' => 'Lombardia','country_id' => '107'),
		  array('id' => '817','name' => 'Marche','country_id' => '107'),
		  array('id' => '818','name' => 'Piemonte','country_id' => '107'),
		  array('id' => '819','name' => 'Sardinia','country_id' => '107'),
		  array('id' => '820','name' => 'Sisilia','country_id' => '107'),
		  array('id' => '821','name' => 'Toscana','country_id' => '107'),
		  array('id' => '822','name' => 'Trentino-Alto Adige','country_id' => '107'),
		  array('id' => '823','name' => 'Umbria','country_id' => '107'),
		  array('id' => '824','name' => 'Veneto','country_id' => '107'),
		  array('id' => '825','name' => 'St. Andrew','country_id' => '108'),
		  array('id' => '826','name' => 'St. Catherine','country_id' => '108'),
		  array('id' => '827','name' => 'al-Zarqa','country_id' => '109'),
		  array('id' => '828','name' => 'Amman','country_id' => '109'),
		  array('id' => '829','name' => 'Irbid','country_id' => '109'),
		  array('id' => '830','name' => 'Aichi','country_id' => '110'),
		  array('id' => '831','name' => 'Akita','country_id' => '110'),
		  array('id' => '832','name' => 'Aomori','country_id' => '110'),
		  array('id' => '833','name' => 'Chiba','country_id' => '110'),
		  array('id' => '834','name' => 'Ehime','country_id' => '110'),
		  array('id' => '835','name' => 'Fukui','country_id' => '110'),
		  array('id' => '836','name' => 'Fukuoka','country_id' => '110'),
		  array('id' => '837','name' => 'Fukushima','country_id' => '110'),
		  array('id' => '838','name' => 'Gifu','country_id' => '110'),
		  array('id' => '839','name' => 'Gumma','country_id' => '110'),
		  array('id' => '840','name' => 'Hiroshima','country_id' => '110'),
		  array('id' => '841','name' => 'Hokkaido','country_id' => '110'),
		  array('id' => '842','name' => 'Hyogo','country_id' => '110'),
		  array('id' => '843','name' => 'Ibaragi','country_id' => '110'),
		  array('id' => '844','name' => 'Ishikawa','country_id' => '110'),
		  array('id' => '845','name' => 'Iwate','country_id' => '110'),
		  array('id' => '846','name' => 'Kagawa','country_id' => '110'),
		  array('id' => '847','name' => 'Kagoshima','country_id' => '110'),
		  array('id' => '848','name' => 'Kanagawa','country_id' => '110'),
		  array('id' => '849','name' => 'Kochi','country_id' => '110'),
		  array('id' => '850','name' => 'Kumamoto','country_id' => '110'),
		  array('id' => '851','name' => 'Kyoto','country_id' => '110'),
		  array('id' => '852','name' => 'Mie','country_id' => '110'),
		  array('id' => '853','name' => 'Miyagi','country_id' => '110'),
		  array('id' => '854','name' => 'Miyazaki','country_id' => '110'),
		  array('id' => '855','name' => 'Nagano','country_id' => '110'),
		  array('id' => '856','name' => 'Nagasaki','country_id' => '110'),
		  array('id' => '857','name' => 'Nara','country_id' => '110'),
		  array('id' => '858','name' => 'Niigata','country_id' => '110'),
		  array('id' => '859','name' => 'Oita','country_id' => '110'),
		  array('id' => '860','name' => 'Okayama','country_id' => '110'),
		  array('id' => '861','name' => 'Okinawa','country_id' => '110'),
		  array('id' => '862','name' => 'Osaka','country_id' => '110'),
		  array('id' => '863','name' => 'Saga','country_id' => '110'),
		  array('id' => '864','name' => 'Saitama','country_id' => '110'),
		  array('id' => '865','name' => 'Shiga','country_id' => '110'),
		  array('id' => '866','name' => 'Shimane','country_id' => '110'),
		  array('id' => '867','name' => 'Shizuoka','country_id' => '110'),
		  array('id' => '868','name' => 'Tochigi','country_id' => '110'),
		  array('id' => '869','name' => 'Tokushima','country_id' => '110'),
		  array('id' => '870','name' => 'Tokyo-to','country_id' => '110'),
		  array('id' => '871','name' => 'Tottori','country_id' => '110'),
		  array('id' => '872','name' => 'Toyama','country_id' => '110'),
		  array('id' => '873','name' => 'Wakayama','country_id' => '110'),
		  array('id' => '874','name' => 'Yamagata','country_id' => '110'),
		  array('id' => '875','name' => 'Yamaguchi','country_id' => '110'),
		  array('id' => '876','name' => 'Yamanashi','country_id' => '110'),
		  array('id' => '877','name' => 'Almaty','country_id' => '111'),
		  array('id' => '878','name' => 'Almaty Qalasy','country_id' => '111'),
		  array('id' => '879','name' => 'AqtÃ¶be','country_id' => '111'),
		  array('id' => '880','name' => 'Astana','country_id' => '111'),
		  array('id' => '881','name' => 'Atyrau','country_id' => '111'),
		  array('id' => '882','name' => 'East Kazakstan','country_id' => '111'),
		  array('id' => '883','name' => 'Mangghystau','country_id' => '111'),
		  array('id' => '884','name' => 'North Kazakstan','country_id' => '111'),
		  array('id' => '885','name' => 'Pavlodar','country_id' => '111'),
		  array('id' => '886','name' => 'Qaraghandy','country_id' => '111'),
		  array('id' => '887','name' => 'Qostanay','country_id' => '111'),
		  array('id' => '888','name' => 'Qyzylorda','country_id' => '111'),
		  array('id' => '889','name' => 'South Kazakstan','country_id' => '111'),
		  array('id' => '890','name' => 'Taraz','country_id' => '111'),
		  array('id' => '891','name' => 'West Kazakstan','country_id' => '111'),
		  array('id' => '892','name' => 'Central','country_id' => '112'),
		  array('id' => '893','name' => 'Coast','country_id' => '112'),
		  array('id' => '894','name' => 'Eastern','country_id' => '112'),
		  array('id' => '895','name' => 'Nairobi','country_id' => '112'),
		  array('id' => '896','name' => 'Nyanza','country_id' => '112'),
		  array('id' => '897','name' => 'Rift Valley','country_id' => '112'),
		  array('id' => '898','name' => 'Bishkek shaary','country_id' => '113'),
		  array('id' => '899','name' => 'Osh','country_id' => '113'),
		  array('id' => '900','name' => 'Battambang','country_id' => '114'),
		  array('id' => '901','name' => 'Phnom Penh','country_id' => '114'),
		  array('id' => '902','name' => 'Siem Reap','country_id' => '114'),
		  array('id' => '903','name' => 'South Tarawa','country_id' => '115'),
		  array('id' => '904','name' => 'St George Basseterre','country_id' => '116'),
		  array('id' => '905','name' => 'Cheju','country_id' => '117'),
		  array('id' => '906','name' => 'Chollabuk','country_id' => '117'),
		  array('id' => '907','name' => 'Chollanam','country_id' => '117'),
		  array('id' => '908','name' => 'Chungchongbuk','country_id' => '117'),
		  array('id' => '909','name' => 'Chungchongnam','country_id' => '117'),
		  array('id' => '910','name' => 'Inchon','country_id' => '117'),
		  array('id' => '911','name' => 'Kang-won','country_id' => '117'),
		  array('id' => '912','name' => 'Kwangju','country_id' => '117'),
		  array('id' => '913','name' => 'Kyonggi','country_id' => '117'),
		  array('id' => '914','name' => 'Kyongsangbuk','country_id' => '117'),
		  array('id' => '915','name' => 'Kyongsangnam','country_id' => '117'),
		  array('id' => '916','name' => 'Pusan','country_id' => '117'),
		  array('id' => '917','name' => 'Seoul','country_id' => '117'),
		  array('id' => '918','name' => 'Taegu','country_id' => '117'),
		  array('id' => '919','name' => 'Taejon','country_id' => '117'),
		  array('id' => '920','name' => 'al-Asima','country_id' => '118'),
		  array('id' => '921','name' => 'Hawalli','country_id' => '118'),
		  array('id' => '922','name' => 'Savannakhet','country_id' => '119'),
		  array('id' => '923','name' => 'Viangchan','country_id' => '119'),
		  array('id' => '924','name' => 'al-Shamal','country_id' => '120'),
		  array('id' => '925','name' => 'Beirut','country_id' => '120'),
		  array('id' => '926','name' => 'Montserrado','country_id' => '121'),
		  array('id' => '927','name' => 'al-Zawiya','country_id' => '122'),
		  array('id' => '928','name' => 'Bengasi','country_id' => '122'),
		  array('id' => '929','name' => 'Misrata','country_id' => '122'),
		  array('id' => '930','name' => 'Tripoli','country_id' => '122'),
		  array('id' => '931','name' => 'Castries','country_id' => '123'),
		  array('id' => '932','name' => 'Schaan','country_id' => '124'),
		  array('id' => '933','name' => 'Vaduz','country_id' => '124'),
		  array('id' => '934','name' => 'Central','country_id' => '125'),
		  array('id' => '935','name' => 'Northern','country_id' => '125'),
		  array('id' => '936','name' => 'Western','country_id' => '125'),
		  array('id' => '937','name' => 'Maseru','country_id' => '126'),
		  array('id' => '938','name' => 'Kaunas','country_id' => '127'),
		  array('id' => '939','name' => 'Klaipeda','country_id' => '127'),
		  array('id' => '940','name' => 'Panevezys','country_id' => '127'),
		  array('id' => '941','name' => 'Vilna','country_id' => '127'),
		  array('id' => '942','name' => 'Å iauliai','country_id' => '127'),
		  array('id' => '943','name' => 'Luxembourg','country_id' => '128'),
		  array('id' => '944','name' => 'Daugavpils','country_id' => '129'),
		  array('id' => '945','name' => 'Liepaja','country_id' => '129'),
		  array('id' => '946','name' => 'Riika','country_id' => '129'),
		  array('id' => '947','name' => 'Macau','country_id' => '130'),
		  array('id' => '948','name' => 'Casablanca','country_id' => '131'),
		  array('id' => '949','name' => 'Chaouia-Ouardigha','country_id' => '131'),
		  array('id' => '950','name' => 'Doukkala-Abda','country_id' => '131'),
		  array('id' => '951','name' => 'FÃ¨s-Boulemane','country_id' => '131'),
		  array('id' => '952','name' => 'Gharb-Chrarda-BÃ©ni','country_id' => '131'),
		  array('id' => '953','name' => 'Marrakech-Tensift-Al','country_id' => '131'),
		  array('id' => '954','name' => 'MeknÃ¨s-Tafilalet','country_id' => '131'),
		  array('id' => '955','name' => 'Oriental','country_id' => '131'),
		  array('id' => '956','name' => 'Rabat-SalÃ©-Zammour-','country_id' => '131'),
		  array('id' => '957','name' => 'Souss Massa-DraÃ¢','country_id' => '131'),
		  array('id' => '958','name' => 'Tadla-Azilal','country_id' => '131'),
		  array('id' => '959','name' => 'Tanger-TÃ©touan','country_id' => '131'),
		  array('id' => '960','name' => 'Taza-Al Hoceima-Taou','country_id' => '131'),
		  array('id' => '961','name' => 'â€“','country_id' => '132'),
		  array('id' => '962','name' => 'Balti','country_id' => '133'),
		  array('id' => '963','name' => 'Bender (TÃ®ghina)','country_id' => '133'),
		  array('id' => '964','name' => 'Chisinau','country_id' => '133'),
		  array('id' => '965','name' => 'Dnjestria','country_id' => '133'),
		  array('id' => '966','name' => 'Antananarivo','country_id' => '134'),
		  array('id' => '967','name' => 'Fianarantsoa','country_id' => '134'),
		  array('id' => '968','name' => 'Mahajanga','country_id' => '134'),
		  array('id' => '969','name' => 'Toamasina','country_id' => '134'),
		  array('id' => '970','name' => 'Maale','country_id' => '135'),
		  array('id' => '971','name' => 'Aguascalientes','country_id' => '136'),
		  array('id' => '972','name' => 'Baja California','country_id' => '136'),
		  array('id' => '973','name' => 'Baja California Sur','country_id' => '136'),
		  array('id' => '974','name' => 'Campeche','country_id' => '136'),
		  array('id' => '975','name' => 'Chiapas','country_id' => '136'),
		  array('id' => '976','name' => 'Chihuahua','country_id' => '136'),
		  array('id' => '977','name' => 'Coahuila de Zaragoza','country_id' => '136'),
		  array('id' => '978','name' => 'Colima','country_id' => '136'),
		  array('id' => '979','name' => 'Distrito Federal','country_id' => '136'),
		  array('id' => '980','name' => 'Durango','country_id' => '136'),
		  array('id' => '981','name' => 'Guanajuato','country_id' => '136'),
		  array('id' => '982','name' => 'Guerrero','country_id' => '136'),
		  array('id' => '983','name' => 'Hidalgo','country_id' => '136'),
		  array('id' => '984','name' => 'Jalisco','country_id' => '136'),
		  array('id' => '985','name' => 'MÃ©xico','country_id' => '136'),
		  array('id' => '986','name' => 'MichoacÃ¡n de Ocampo','country_id' => '136'),
		  array('id' => '987','name' => 'Morelos','country_id' => '136'),
		  array('id' => '988','name' => 'Nayarit','country_id' => '136'),
		  array('id' => '989','name' => 'Nuevo LeÃ³n','country_id' => '136'),
		  array('id' => '990','name' => 'Oaxaca','country_id' => '136'),
		  array('id' => '991','name' => 'Puebla','country_id' => '136'),
		  array('id' => '992','name' => 'QuerÃ©taro','country_id' => '136'),
		  array('id' => '993','name' => 'QuerÃ©taro de Arteag','country_id' => '136'),
		  array('id' => '994','name' => 'Quintana Roo','country_id' => '136'),
		  array('id' => '995','name' => 'San Luis PotosÃ­','country_id' => '136'),
		  array('id' => '996','name' => 'Sinaloa','country_id' => '136'),
		  array('id' => '997','name' => 'Sonora','country_id' => '136'),
		  array('id' => '998','name' => 'Tabasco','country_id' => '136'),
		  array('id' => '999','name' => 'Tamaulipas','country_id' => '136'),
		  array('id' => '1000','name' => 'Veracruz','country_id' => '136'),
		  array('id' => '1001','name' => 'Veracruz-Llave','country_id' => '136'),
		  array('id' => '1002','name' => 'YucatÃ¡n','country_id' => '136'),
		  array('id' => '1003','name' => 'Zacatecas','country_id' => '136'),
		  array('id' => '1004','name' => 'Majuro','country_id' => '137'),
		  array('id' => '1005','name' => 'Skopje','country_id' => '138'),
		  array('id' => '1006','name' => 'Bamako','country_id' => '139'),
		  array('id' => '1007','name' => 'Inner Harbour','country_id' => '140'),
		  array('id' => '1008','name' => 'Outer Harbour','country_id' => '140'),
		  array('id' => '1009','name' => 'Irrawaddy [Ayeyarwad','country_id' => '141'),
		  array('id' => '1010','name' => 'Magwe [Magway]','country_id' => '141'),
		  array('id' => '1011','name' => 'Mandalay','country_id' => '141'),
		  array('id' => '1012','name' => 'Mon','country_id' => '141'),
		  array('id' => '1013','name' => 'Pegu [Bago]','country_id' => '141'),
		  array('id' => '1014','name' => 'Rakhine','country_id' => '141'),
		  array('id' => '1015','name' => 'Rangoon [Yangon]','country_id' => '141'),
		  array('id' => '1016','name' => 'Sagaing','country_id' => '141'),
		  array('id' => '1017','name' => 'Shan','country_id' => '141'),
		  array('id' => '1018','name' => 'Tenasserim [Tanintha','country_id' => '141'),
		  array('id' => '1019','name' => 'Ulaanbaatar','country_id' => '142'),
		  array('id' => '1020','name' => 'Saipan','country_id' => '143'),
		  array('id' => '1021','name' => 'Gaza','country_id' => '144'),
		  array('id' => '1022','name' => 'Inhambane','country_id' => '144'),
		  array('id' => '1023','name' => 'Manica','country_id' => '144'),
		  array('id' => '1024','name' => 'Maputo','country_id' => '144'),
		  array('id' => '1025','name' => 'Nampula','country_id' => '144'),
		  array('id' => '1026','name' => 'Sofala','country_id' => '144'),
		  array('id' => '1027','name' => 'Tete','country_id' => '144'),
		  array('id' => '1028','name' => 'ZambÃ©zia','country_id' => '144'),
		  array('id' => '1029','name' => 'Dakhlet NouÃ¢dhibou','country_id' => '145'),
		  array('id' => '1030','name' => 'Nouakchott','country_id' => '145'),
		  array('id' => '1031','name' => 'Plymouth','country_id' => '146'),
		  array('id' => '1032','name' => 'Fort-de-France','country_id' => '147'),
		  array('id' => '1033','name' => 'Plaines Wilhelms','country_id' => '148'),
		  array('id' => '1034','name' => 'Port-Louis','country_id' => '148'),
		  array('id' => '1035','name' => 'Blantyre','country_id' => '149'),
		  array('id' => '1036','name' => 'Lilongwe','country_id' => '149'),
		  array('id' => '1037','name' => 'Johor','country_id' => '150'),
		  array('id' => '1038','name' => 'Kedah','country_id' => '150'),
		  array('id' => '1039','name' => 'Kelantan','country_id' => '150'),
		  array('id' => '1040','name' => 'Negeri Sembilan','country_id' => '150'),
		  array('id' => '1041','name' => 'Pahang','country_id' => '150'),
		  array('id' => '1042','name' => 'Perak','country_id' => '150'),
		  array('id' => '1043','name' => 'Pulau Pinang','country_id' => '150'),
		  array('id' => '1044','name' => 'Sabah','country_id' => '150'),
		  array('id' => '1045','name' => 'Sarawak','country_id' => '150'),
		  array('id' => '1046','name' => 'Selangor','country_id' => '150'),
		  array('id' => '1047','name' => 'Terengganu','country_id' => '150'),
		  array('id' => '1048','name' => 'Wilayah Persekutuan','country_id' => '150'),
		  array('id' => '1049','name' => 'Mamoutzou','country_id' => '151'),
		  array('id' => '1050','name' => 'Khomas','country_id' => '152'),
		  array('id' => '1051','name' => 'â€“','country_id' => '153'),
		  array('id' => '1052','name' => 'Maradi','country_id' => '154'),
		  array('id' => '1053','name' => 'Niamey','country_id' => '154'),
		  array('id' => '1054','name' => 'Zinder','country_id' => '154'),
		  array('id' => '1055','name' => 'â€“','country_id' => '155'),
		  array('id' => '1056','name' => 'Anambra & Enugu & Eb','country_id' => '156'),
		  array('id' => '1057','name' => 'Bauchi & Gombe','country_id' => '156'),
		  array('id' => '1058','name' => 'Benue','country_id' => '156'),
		  array('id' => '1059','name' => 'Borno & Yobe','country_id' => '156'),
		  array('id' => '1060','name' => 'Cross River','country_id' => '156'),
		  array('id' => '1061','name' => 'Edo & Delta','country_id' => '156'),
		  array('id' => '1062','name' => 'Federal Capital Dist','country_id' => '156'),
		  array('id' => '1063','name' => 'Imo & Abia','country_id' => '156'),
		  array('id' => '1064','name' => 'Kaduna','country_id' => '156'),
		  array('id' => '1065','name' => 'Kano & Jigawa','country_id' => '156'),
		  array('id' => '1066','name' => 'Katsina','country_id' => '156'),
		  array('id' => '1067','name' => 'Kwara & Kogi','country_id' => '156'),
		  array('id' => '1068','name' => 'Lagos','country_id' => '156'),
		  array('id' => '1069','name' => 'Niger','country_id' => '156'),
		  array('id' => '1070','name' => 'Ogun','country_id' => '156'),
		  array('id' => '1071','name' => 'Ondo & Ekiti','country_id' => '156'),
		  array('id' => '1072','name' => 'Oyo & Osun','country_id' => '156'),
		  array('id' => '1073','name' => 'Plateau & Nassarawa','country_id' => '156'),
		  array('id' => '1074','name' => 'Rivers & Bayelsa','country_id' => '156'),
		  array('id' => '1075','name' => 'Sokoto & Kebbi & Zam','country_id' => '156'),
		  array('id' => '1076','name' => 'Chinandega','country_id' => '157'),
		  array('id' => '1077','name' => 'LeÃ³n','country_id' => '157'),
		  array('id' => '1078','name' => 'Managua','country_id' => '157'),
		  array('id' => '1079','name' => 'Masaya','country_id' => '157'),
		  array('id' => '1080','name' => 'â€“','country_id' => '158'),
		  array('id' => '1081','name' => 'Drenthe','country_id' => '159'),
		  array('id' => '1082','name' => 'Flevoland','country_id' => '159'),
		  array('id' => '1083','name' => 'Gelderland','country_id' => '159'),
		  array('id' => '1084','name' => 'Groningen','country_id' => '159'),
		  array('id' => '1085','name' => 'Limburg','country_id' => '159'),
		  array('id' => '1086','name' => 'Noord-Brabant','country_id' => '159'),
		  array('id' => '1087','name' => 'Noord-Holland','country_id' => '159'),
		  array('id' => '1088','name' => 'Overijssel','country_id' => '159'),
		  array('id' => '1089','name' => 'Utrecht','country_id' => '159'),
		  array('id' => '1090','name' => 'Zuid-Holland','country_id' => '159'),
		  array('id' => '1091','name' => 'Akershus','country_id' => '160'),
		  array('id' => '1092','name' => 'Hordaland','country_id' => '160'),
		  array('id' => '1093','name' => 'Oslo','country_id' => '160'),
		  array('id' => '1094','name' => 'Rogaland','country_id' => '160'),
		  array('id' => '1095','name' => 'SÃ¸r-TrÃ¸ndelag','country_id' => '160'),
		  array('id' => '1096','name' => 'Central','country_id' => '161'),
		  array('id' => '1097','name' => 'Eastern','country_id' => '161'),
		  array('id' => '1098','name' => 'Western','country_id' => '161'),
		  array('id' => '1099','name' => 'â€“','country_id' => '162'),
		  array('id' => '1100','name' => 'Auckland','country_id' => '163'),
		  array('id' => '1101','name' => 'Canterbury','country_id' => '163'),
		  array('id' => '1102','name' => 'Dunedin','country_id' => '163'),
		  array('id' => '1103','name' => 'Hamilton','country_id' => '163'),
		  array('id' => '1104','name' => 'Wellington','country_id' => '163'),
		  array('id' => '1105','name' => 'al-Batina','country_id' => '164'),
		  array('id' => '1106','name' => 'Masqat','country_id' => '164'),
		  array('id' => '1107','name' => 'Zufar','country_id' => '164'),
		  array('id' => '1108','name' => 'Baluchistan','country_id' => '165'),
		  array('id' => '1109','name' => 'Islamabad','country_id' => '165'),
		  array('id' => '1110','name' => 'Nothwest Border Prov','country_id' => '165'),
		  array('id' => '1111','name' => 'Punjab','country_id' => '165'),
		  array('id' => '1112','name' => 'Sind','country_id' => '165'),
		  array('id' => '1113','name' => 'Sindh','country_id' => '165'),
		  array('id' => '1114','name' => 'PanamÃ¡','country_id' => '166'),
		  array('id' => '1115','name' => 'San Miguelito','country_id' => '166'),
		  array('id' => '1116','name' => 'â€“','country_id' => '167'),
		  array('id' => '1117','name' => 'Ancash','country_id' => '168'),
		  array('id' => '1118','name' => 'Arequipa','country_id' => '168'),
		  array('id' => '1119','name' => 'Ayacucho','country_id' => '168'),
		  array('id' => '1120','name' => 'Cajamarca','country_id' => '168'),
		  array('id' => '1121','name' => 'Callao','country_id' => '168'),
		  array('id' => '1122','name' => 'Cusco','country_id' => '168'),
		  array('id' => '1123','name' => 'Huanuco','country_id' => '168'),
		  array('id' => '1124','name' => 'Ica','country_id' => '168'),
		  array('id' => '1125','name' => 'JunÃ­n','country_id' => '168'),
		  array('id' => '1126','name' => 'La Libertad','country_id' => '168'),
		  array('id' => '1127','name' => 'Lambayeque','country_id' => '168'),
		  array('id' => '1128','name' => 'Lima','country_id' => '168'),
		  array('id' => '1129','name' => 'Loreto','country_id' => '168'),
		  array('id' => '1130','name' => 'Piura','country_id' => '168'),
		  array('id' => '1131','name' => 'Puno','country_id' => '168'),
		  array('id' => '1132','name' => 'Tacna','country_id' => '168'),
		  array('id' => '1133','name' => 'Ucayali','country_id' => '168'),
		  array('id' => '1134','name' => 'ARMM','country_id' => '169'),
		  array('id' => '1135','name' => 'Bicol','country_id' => '169'),
		  array('id' => '1136','name' => 'Cagayan Valley','country_id' => '169'),
		  array('id' => '1137','name' => 'CAR','country_id' => '169'),
		  array('id' => '1138','name' => 'Caraga','country_id' => '169'),
		  array('id' => '1139','name' => 'Central Luzon','country_id' => '169'),
		  array('id' => '1140','name' => 'Central Mindanao','country_id' => '169'),
		  array('id' => '1141','name' => 'Central Visayas','country_id' => '169'),
		  array('id' => '1142','name' => 'Eastern Visayas','country_id' => '169'),
		  array('id' => '1143','name' => 'Ilocos','country_id' => '169'),
		  array('id' => '1144','name' => 'National Capital Reg','country_id' => '169'),
		  array('id' => '1145','name' => 'Northern Mindanao','country_id' => '169'),
		  array('id' => '1146','name' => 'Southern Mindanao','country_id' => '169'),
		  array('id' => '1147','name' => 'Southern Tagalog','country_id' => '169'),
		  array('id' => '1148','name' => 'Western Mindanao','country_id' => '169'),
		  array('id' => '1149','name' => 'Western Visayas','country_id' => '169'),
		  array('id' => '1150','name' => 'Koror','country_id' => '170'),
		  array('id' => '1151','name' => 'National Capital Dis','country_id' => '171'),
		  array('id' => '1152','name' => 'Dolnoslaskie','country_id' => '172'),
		  array('id' => '1153','name' => 'Kujawsko-Pomorskie','country_id' => '172'),
		  array('id' => '1154','name' => 'Lodzkie','country_id' => '172'),
		  array('id' => '1155','name' => 'Lubelskie','country_id' => '172'),
		  array('id' => '1156','name' => 'Lubuskie','country_id' => '172'),
		  array('id' => '1157','name' => 'Malopolskie','country_id' => '172'),
		  array('id' => '1158','name' => 'Mazowieckie','country_id' => '172'),
		  array('id' => '1159','name' => 'Opolskie','country_id' => '172'),
		  array('id' => '1160','name' => 'Podkarpackie','country_id' => '172'),
		  array('id' => '1161','name' => 'Podlaskie','country_id' => '172'),
		  array('id' => '1162','name' => 'Pomorskie','country_id' => '172'),
		  array('id' => '1163','name' => 'Slaskie','country_id' => '172'),
		  array('id' => '1164','name' => 'Swietokrzyskie','country_id' => '172'),
		  array('id' => '1165','name' => 'Warminsko-Mazurskie','country_id' => '172'),
		  array('id' => '1166','name' => 'Wielkopolskie','country_id' => '172'),
		  array('id' => '1167','name' => 'Zachodnio-Pomorskie','country_id' => '172'),
		  array('id' => '1168','name' => 'Arecibo','country_id' => '173'),
		  array('id' => '1169','name' => 'BayamÃ³n','country_id' => '173'),
		  array('id' => '1170','name' => 'Caguas','country_id' => '173'),
		  array('id' => '1171','name' => 'Carolina','country_id' => '173'),
		  array('id' => '1172','name' => 'Guaynabo','country_id' => '173'),
		  array('id' => '1173','name' => 'MayagÃ¼ez','country_id' => '173'),
		  array('id' => '1174','name' => 'Ponce','country_id' => '173'),
		  array('id' => '1175','name' => 'San Juan','country_id' => '173'),
		  array('id' => '1176','name' => 'Toa Baja','country_id' => '173'),
		  array('id' => '1177','name' => 'Chagang','country_id' => '174'),
		  array('id' => '1178','name' => 'Hamgyong N','country_id' => '174'),
		  array('id' => '1179','name' => 'Hamgyong P','country_id' => '174'),
		  array('id' => '1180','name' => 'Hwanghae N','country_id' => '174'),
		  array('id' => '1181','name' => 'Hwanghae P','country_id' => '174'),
		  array('id' => '1182','name' => 'Kaesong-si','country_id' => '174'),
		  array('id' => '1183','name' => 'Kangwon','country_id' => '174'),
		  array('id' => '1184','name' => 'Nampo-si','country_id' => '174'),
		  array('id' => '1185','name' => 'Pyongan N','country_id' => '174'),
		  array('id' => '1186','name' => 'Pyongan P','country_id' => '174'),
		  array('id' => '1187','name' => 'Pyongyang-si','country_id' => '174'),
		  array('id' => '1188','name' => 'Yanggang','country_id' => '174'),
		  array('id' => '1189','name' => 'Braga','country_id' => '175'),
		  array('id' => '1190','name' => 'CoÃ­mbra','country_id' => '175'),
		  array('id' => '1191','name' => 'Lisboa','country_id' => '175'),
		  array('id' => '1192','name' => 'Porto','country_id' => '175'),
		  array('id' => '1193','name' => 'Alto ParanÃ¡','country_id' => '176'),
		  array('id' => '1194','name' => 'AsunciÃ³n','country_id' => '176'),
		  array('id' => '1195','name' => 'Central','country_id' => '176'),
		  array('id' => '1196','name' => 'Gaza','country_id' => '177'),
		  array('id' => '1197','name' => 'Hebron','country_id' => '177'),
		  array('id' => '1198','name' => 'Khan Yunis','country_id' => '177'),
		  array('id' => '1199','name' => 'Nablus','country_id' => '177'),
		  array('id' => '1200','name' => 'North Gaza','country_id' => '177'),
		  array('id' => '1201','name' => 'Rafah','country_id' => '177'),
		  array('id' => '1202','name' => 'Tahiti','country_id' => '178'),
		  array('id' => '1203','name' => 'Doha','country_id' => '179'),
		  array('id' => '1204','name' => 'Saint-Denis','country_id' => '180'),
		  array('id' => '1205','name' => 'Arad','country_id' => '181'),
		  array('id' => '1206','name' => 'Arges','country_id' => '181'),
		  array('id' => '1207','name' => 'Bacau','country_id' => '181'),
		  array('id' => '1208','name' => 'Bihor','country_id' => '181'),
		  array('id' => '1209','name' => 'Botosani','country_id' => '181'),
		  array('id' => '1210','name' => 'Braila','country_id' => '181'),
		  array('id' => '1211','name' => 'Brasov','country_id' => '181'),
		  array('id' => '1212','name' => 'Bukarest','country_id' => '181'),
		  array('id' => '1213','name' => 'Buzau','country_id' => '181'),
		  array('id' => '1214','name' => 'Caras-Severin','country_id' => '181'),
		  array('id' => '1215','name' => 'Cluj','country_id' => '181'),
		  array('id' => '1216','name' => 'Constanta','country_id' => '181'),
		  array('id' => '1217','name' => 'DÃ¢mbovita','country_id' => '181'),
		  array('id' => '1218','name' => 'Dolj','country_id' => '181'),
		  array('id' => '1219','name' => 'Galati','country_id' => '181'),
		  array('id' => '1220','name' => 'Gorj','country_id' => '181'),
		  array('id' => '1221','name' => 'Iasi','country_id' => '181'),
		  array('id' => '1222','name' => 'Maramures','country_id' => '181'),
		  array('id' => '1223','name' => 'Mehedinti','country_id' => '181'),
		  array('id' => '1224','name' => 'Mures','country_id' => '181'),
		  array('id' => '1225','name' => 'Neamt','country_id' => '181'),
		  array('id' => '1226','name' => 'Prahova','country_id' => '181'),
		  array('id' => '1227','name' => 'Satu Mare','country_id' => '181'),
		  array('id' => '1228','name' => 'Sibiu','country_id' => '181'),
		  array('id' => '1229','name' => 'Suceava','country_id' => '181'),
		  array('id' => '1230','name' => 'Timis','country_id' => '181'),
		  array('id' => '1231','name' => 'Tulcea','country_id' => '181'),
		  array('id' => '1232','name' => 'VÃ¢lcea','country_id' => '181'),
		  array('id' => '1233','name' => 'Vrancea','country_id' => '181'),
		  array('id' => '1234','name' => 'Adygea','country_id' => '182'),
		  array('id' => '1235','name' => 'Altai','country_id' => '182'),
		  array('id' => '1236','name' => 'Amur','country_id' => '182'),
		  array('id' => '1237','name' => 'Arkangeli','country_id' => '182'),
		  array('id' => '1238','name' => 'Astrahan','country_id' => '182'),
		  array('id' => '1239','name' => 'BaÅ¡kortostan','country_id' => '182'),
		  array('id' => '1240','name' => 'Belgorod','country_id' => '182'),
		  array('id' => '1241','name' => 'Brjansk','country_id' => '182'),
		  array('id' => '1242','name' => 'Burjatia','country_id' => '182'),
		  array('id' => '1243','name' => 'Dagestan','country_id' => '182'),
		  array('id' => '1244','name' => 'Habarovsk','country_id' => '182'),
		  array('id' => '1245','name' => 'Hakassia','country_id' => '182'),
		  array('id' => '1246','name' => 'Hanti-Mansia','country_id' => '182'),
		  array('id' => '1247','name' => 'Irkutsk','country_id' => '182'),
		  array('id' => '1248','name' => 'Ivanovo','country_id' => '182'),
		  array('id' => '1249','name' => 'Jaroslavl','country_id' => '182'),
		  array('id' => '1250','name' => 'Kabardi-Balkaria','country_id' => '182'),
		  array('id' => '1251','name' => 'Kaliningrad','country_id' => '182'),
		  array('id' => '1252','name' => 'Kalmykia','country_id' => '182'),
		  array('id' => '1253','name' => 'Kaluga','country_id' => '182'),
		  array('id' => '1254','name' => 'KamtÅ¡atka','country_id' => '182'),
		  array('id' => '1255','name' => 'KaratÅ¡ai-TÅ¡erkessi','country_id' => '182'),
		  array('id' => '1256','name' => 'Karjala','country_id' => '182'),
		  array('id' => '1257','name' => 'Kemerovo','country_id' => '182'),
		  array('id' => '1258','name' => 'Kirov','country_id' => '182'),
		  array('id' => '1259','name' => 'Komi','country_id' => '182'),
		  array('id' => '1260','name' => 'Kostroma','country_id' => '182'),
		  array('id' => '1261','name' => 'Krasnodar','country_id' => '182'),
		  array('id' => '1262','name' => 'Krasnojarsk','country_id' => '182'),
		  array('id' => '1263','name' => 'Kurgan','country_id' => '182'),
		  array('id' => '1264','name' => 'Kursk','country_id' => '182'),
		  array('id' => '1265','name' => 'Lipetsk','country_id' => '182'),
		  array('id' => '1266','name' => 'Magadan','country_id' => '182'),
		  array('id' => '1267','name' => 'Marinmaa','country_id' => '182'),
		  array('id' => '1268','name' => 'Mordva','country_id' => '182'),
		  array('id' => '1269','name' => 'Moscow (City)','country_id' => '182'),
		  array('id' => '1270','name' => 'Moskova','country_id' => '182'),
		  array('id' => '1271','name' => 'Murmansk','country_id' => '182'),
		  array('id' => '1272','name' => 'Nizni Novgorod','country_id' => '182'),
		  array('id' => '1273','name' => 'North Ossetia-Alania','country_id' => '182'),
		  array('id' => '1274','name' => 'Novgorod','country_id' => '182'),
		  array('id' => '1275','name' => 'Novosibirsk','country_id' => '182'),
		  array('id' => '1276','name' => 'Omsk','country_id' => '182'),
		  array('id' => '1277','name' => 'Orenburg','country_id' => '182'),
		  array('id' => '1278','name' => 'Orjol','country_id' => '182'),
		  array('id' => '1279','name' => 'Penza','country_id' => '182'),
		  array('id' => '1280','name' => 'Perm','country_id' => '182'),
		  array('id' => '1281','name' => 'Pietari','country_id' => '182'),
		  array('id' => '1282','name' => 'Pihkova','country_id' => '182'),
		  array('id' => '1283','name' => 'Primorje','country_id' => '182'),
		  array('id' => '1284','name' => 'Rjazan','country_id' => '182'),
		  array('id' => '1285','name' => 'Rostov-na-Donu','country_id' => '182'),
		  array('id' => '1286','name' => 'Saha (Jakutia)','country_id' => '182'),
		  array('id' => '1287','name' => 'Sahalin','country_id' => '182'),
		  array('id' => '1288','name' => 'Samara','country_id' => '182'),
		  array('id' => '1289','name' => 'Saratov','country_id' => '182'),
		  array('id' => '1290','name' => 'Smolensk','country_id' => '182'),
		  array('id' => '1291','name' => 'Stavropol','country_id' => '182'),
		  array('id' => '1292','name' => 'Sverdlovsk','country_id' => '182'),
		  array('id' => '1293','name' => 'Tambov','country_id' => '182'),
		  array('id' => '1294','name' => 'Tatarstan','country_id' => '182'),
		  array('id' => '1295','name' => 'Tjumen','country_id' => '182'),
		  array('id' => '1296','name' => 'Tomsk','country_id' => '182'),
		  array('id' => '1297','name' => 'Tula','country_id' => '182'),
		  array('id' => '1298','name' => 'Tver','country_id' => '182'),
		  array('id' => '1299','name' => 'Tyva','country_id' => '182'),
		  array('id' => '1300','name' => 'TÅ¡eljabinsk','country_id' => '182'),
		  array('id' => '1301','name' => 'TÅ¡etÅ¡enia','country_id' => '182'),
		  array('id' => '1302','name' => 'TÅ¡ita','country_id' => '182'),
		  array('id' => '1303','name' => 'TÅ¡uvassia','country_id' => '182'),
		  array('id' => '1304','name' => 'Udmurtia','country_id' => '182'),
		  array('id' => '1305','name' => 'Uljanovsk','country_id' => '182'),
		  array('id' => '1306','name' => 'Vladimir','country_id' => '182'),
		  array('id' => '1307','name' => 'Volgograd','country_id' => '182'),
		  array('id' => '1308','name' => 'Vologda','country_id' => '182'),
		  array('id' => '1309','name' => 'Voronez','country_id' => '182'),
		  array('id' => '1310','name' => 'Yamalin Nenetsia','country_id' => '182'),
		  array('id' => '1311','name' => 'Kigali','country_id' => '183'),
		  array('id' => '1312','name' => 'al-Khudud al-Samaliy','country_id' => '184'),
		  array('id' => '1313','name' => 'al-Qasim','country_id' => '184'),
		  array('id' => '1314','name' => 'al-Sharqiya','country_id' => '184'),
		  array('id' => '1315','name' => 'Asir','country_id' => '184'),
		  array('id' => '1316','name' => 'Hail','country_id' => '184'),
		  array('id' => '1317','name' => 'Medina','country_id' => '184'),
		  array('id' => '1318','name' => 'Mekka','country_id' => '184'),
		  array('id' => '1319','name' => 'Najran','country_id' => '184'),
		  array('id' => '1320','name' => 'Qasim','country_id' => '184'),
		  array('id' => '1321','name' => 'Riad','country_id' => '184'),
		  array('id' => '1322','name' => 'Riyadh','country_id' => '184'),
		  array('id' => '1323','name' => 'Tabuk','country_id' => '184'),
		  array('id' => '1324','name' => 'al-Bahr al-Abyad','country_id' => '185'),
		  array('id' => '1325','name' => 'al-Bahr al-Ahmar','country_id' => '185'),
		  array('id' => '1326','name' => 'al-Jazira','country_id' => '185'),
		  array('id' => '1327','name' => 'al-Qadarif','country_id' => '185'),
		  array('id' => '1328','name' => 'Bahr al-Jabal','country_id' => '185'),
		  array('id' => '1329','name' => 'Darfur al-Janubiya','country_id' => '185'),
		  array('id' => '1330','name' => 'Darfur al-Shamaliya','country_id' => '185'),
		  array('id' => '1331','name' => 'Kassala','country_id' => '185'),
		  array('id' => '1332','name' => 'Khartum','country_id' => '185'),
		  array('id' => '1333','name' => 'Kurdufan al-Shamaliy','country_id' => '185'),
		  array('id' => '1334','name' => 'Cap-Vert','country_id' => '186'),
		  array('id' => '1335','name' => 'Diourbel','country_id' => '186'),
		  array('id' => '1336','name' => 'Kaolack','country_id' => '186'),
		  array('id' => '1337','name' => 'Saint-Louis','country_id' => '186'),
		  array('id' => '1338','name' => 'ThiÃ¨s','country_id' => '186'),
		  array('id' => '1339','name' => 'Ziguinchor','country_id' => '186'),
		  array('id' => '1340','name' => 'â€“','country_id' => '187'),
		  array('id' => '1341','name' => 'Saint Helena','country_id' => '189'),
		  array('id' => '1342','name' => 'LÃ¤nsimaa','country_id' => '190'),
		  array('id' => '1343','name' => 'Honiara','country_id' => '191'),
		  array('id' => '1344','name' => 'Western','country_id' => '192'),
		  array('id' => '1345','name' => 'La Libertad','country_id' => '193'),
		  array('id' => '1346','name' => 'San Miguel','country_id' => '193'),
		  array('id' => '1347','name' => 'San Salvador','country_id' => '193'),
		  array('id' => '1348','name' => 'Santa Ana','country_id' => '193'),
		  array('id' => '1349','name' => 'San Marino','country_id' => '194'),
		  array('id' => '1350','name' => 'Serravalle/Dogano','country_id' => '194'),
		  array('id' => '1351','name' => 'Banaadir','country_id' => '195'),
		  array('id' => '1352','name' => 'Jubbada Hoose','country_id' => '195'),
		  array('id' => '1353','name' => 'Woqooyi Galbeed','country_id' => '195'),
		  array('id' => '1354','name' => 'Saint-Pierre','country_id' => '196'),
		  array('id' => '1355','name' => 'Aqua Grande','country_id' => '197'),
		  array('id' => '1356','name' => 'Paramaribo','country_id' => '198'),
		  array('id' => '1357','name' => 'Bratislava','country_id' => '199'),
		  array('id' => '1358','name' => 'VÃ½chodnÃ© Slovensko','country_id' => '199'),
		  array('id' => '1359','name' => 'Osrednjeslovenska','country_id' => '200'),
		  array('id' => '1360','name' => 'Podravska','country_id' => '200'),
		  array('id' => '1361','name' => 'Ã–rebros lÃ¤n','country_id' => '201'),
		  array('id' => '1362','name' => 'East GÃ¶tanmaan lÃ¤n','country_id' => '201'),
		  array('id' => '1363','name' => 'GÃ¤vleborgs lÃ¤n','country_id' => '201'),
		  array('id' => '1364','name' => 'JÃ¶nkÃ¶pings lÃ¤n','country_id' => '201'),
		  array('id' => '1365','name' => 'Lisboa','country_id' => '201'),
		  array('id' => '1366','name' => 'SkÃ¥ne lÃ¤n','country_id' => '201'),
		  array('id' => '1367','name' => 'Uppsala lÃ¤n','country_id' => '201'),
		  array('id' => '1368','name' => 'VÃ¤sterbottens lÃ¤n','country_id' => '201'),
		  array('id' => '1369','name' => 'VÃ¤sternorrlands lÃ¤','country_id' => '201'),
		  array('id' => '1370','name' => 'VÃ¤stmanlands lÃ¤n','country_id' => '201'),
		  array('id' => '1371','name' => 'West GÃ¶tanmaan lÃ¤n','country_id' => '201'),
		  array('id' => '1372','name' => 'Hhohho','country_id' => '202'),
		  array('id' => '1373','name' => 'MahÃ©','country_id' => '203'),
		  array('id' => '1374','name' => 'al-Hasaka','country_id' => '204'),
		  array('id' => '1375','name' => 'al-Raqqa','country_id' => '204'),
		  array('id' => '1376','name' => 'Aleppo','country_id' => '204'),
		  array('id' => '1377','name' => 'Damascus','country_id' => '204'),
		  array('id' => '1378','name' => 'Damaskos','country_id' => '204'),
		  array('id' => '1379','name' => 'Dayr al-Zawr','country_id' => '204'),
		  array('id' => '1380','name' => 'Hama','country_id' => '204'),
		  array('id' => '1381','name' => 'Hims','country_id' => '204'),
		  array('id' => '1382','name' => 'Idlib','country_id' => '204'),
		  array('id' => '1383','name' => 'Latakia','country_id' => '204'),
		  array('id' => '1384','name' => 'Grand Turk','country_id' => '205'),
		  array('id' => '1385','name' => 'Chari-Baguirmi','country_id' => '206'),
		  array('id' => '1386','name' => 'Logone Occidental','country_id' => '206'),
		  array('id' => '1387','name' => 'Maritime','country_id' => '207'),
		  array('id' => '1388','name' => 'Bangkok','country_id' => '208'),
		  array('id' => '1389','name' => 'Chiang Mai','country_id' => '208'),
		  array('id' => '1390','name' => 'Khon Kaen','country_id' => '208'),
		  array('id' => '1391','name' => 'Nakhon Pathom','country_id' => '208'),
		  array('id' => '1392','name' => 'Nakhon Ratchasima','country_id' => '208'),
		  array('id' => '1393','name' => 'Nakhon Sawan','country_id' => '208'),
		  array('id' => '1394','name' => 'Nonthaburi','country_id' => '208'),
		  array('id' => '1395','name' => 'Songkhla','country_id' => '208'),
		  array('id' => '1396','name' => 'Ubon Ratchathani','country_id' => '208'),
		  array('id' => '1397','name' => 'Udon Thani','country_id' => '208'),
		  array('id' => '1398','name' => 'Karotegin','country_id' => '209'),
		  array('id' => '1399','name' => 'Khujand','country_id' => '209'),
		  array('id' => '1400','name' => 'Fakaofo','country_id' => '210'),
		  array('id' => '1401','name' => 'Ahal','country_id' => '211'),
		  array('id' => '1402','name' => 'Dashhowuz','country_id' => '211'),
		  array('id' => '1403','name' => 'Lebap','country_id' => '211'),
		  array('id' => '1404','name' => 'Mary','country_id' => '211'),
		  array('id' => '1405','name' => 'Dili','country_id' => '212'),
		  array('id' => '1406','name' => 'Tongatapu','country_id' => '213'),
		  array('id' => '1407','name' => 'Caroni','country_id' => '214'),
		  array('id' => '1408','name' => 'Port-of-Spain','country_id' => '214'),
		  array('id' => '1409','name' => 'Ariana','country_id' => '215'),
		  array('id' => '1410','name' => 'Biserta','country_id' => '215'),
		  array('id' => '1411','name' => 'GabÃ¨s','country_id' => '215'),
		  array('id' => '1412','name' => 'Kairouan','country_id' => '215'),
		  array('id' => '1413','name' => 'Sfax','country_id' => '215'),
		  array('id' => '1414','name' => 'Sousse','country_id' => '215'),
		  array('id' => '1415','name' => 'Tunis','country_id' => '215'),
		  array('id' => '1416','name' => 'Adana','country_id' => '216'),
		  array('id' => '1417','name' => 'Adiyaman','country_id' => '216'),
		  array('id' => '1418','name' => 'Afyon','country_id' => '216'),
		  array('id' => '1419','name' => 'Aksaray','country_id' => '216'),
		  array('id' => '1420','name' => 'Ankara','country_id' => '216'),
		  array('id' => '1421','name' => 'Antalya','country_id' => '216'),
		  array('id' => '1422','name' => 'Aydin','country_id' => '216'),
		  array('id' => '1423','name' => 'Ã‡orum','country_id' => '216'),
		  array('id' => '1424','name' => 'Balikesir','country_id' => '216'),
		  array('id' => '1425','name' => 'Batman','country_id' => '216'),
		  array('id' => '1426','name' => 'Bursa','country_id' => '216'),
		  array('id' => '1427','name' => 'Denizli','country_id' => '216'),
		  array('id' => '1428','name' => 'Diyarbakir','country_id' => '216'),
		  array('id' => '1429','name' => 'Edirne','country_id' => '216'),
		  array('id' => '1430','name' => 'ElÃ¢zig','country_id' => '216'),
		  array('id' => '1431','name' => 'Erzincan','country_id' => '216'),
		  array('id' => '1432','name' => 'Erzurum','country_id' => '216'),
		  array('id' => '1433','name' => 'Eskisehir','country_id' => '216'),
		  array('id' => '1434','name' => 'Gaziantep','country_id' => '216'),
		  array('id' => '1435','name' => 'Hatay','country_id' => '216'),
		  array('id' => '1436','name' => 'IÃ§el','country_id' => '216'),
		  array('id' => '1437','name' => 'Isparta','country_id' => '216'),
		  array('id' => '1438','name' => 'Istanbul','country_id' => '216'),
		  array('id' => '1439','name' => 'Izmir','country_id' => '216'),
		  array('id' => '1440','name' => 'Kahramanmaras','country_id' => '216'),
		  array('id' => '1441','name' => 'KarabÃ¼k','country_id' => '216'),
		  array('id' => '1442','name' => 'Karaman','country_id' => '216'),
		  array('id' => '1443','name' => 'Kars','country_id' => '216'),
		  array('id' => '1444','name' => 'Kayseri','country_id' => '216'),
		  array('id' => '1445','name' => 'KÃ¼tahya','country_id' => '216'),
		  array('id' => '1446','name' => 'Kilis','country_id' => '216'),
		  array('id' => '1447','name' => 'Kirikkale','country_id' => '216'),
		  array('id' => '1448','name' => 'Kocaeli','country_id' => '216'),
		  array('id' => '1449','name' => 'Konya','country_id' => '216'),
		  array('id' => '1450','name' => 'Malatya','country_id' => '216'),
		  array('id' => '1451','name' => 'Manisa','country_id' => '216'),
		  array('id' => '1452','name' => 'Mardin','country_id' => '216'),
		  array('id' => '1453','name' => 'Ordu','country_id' => '216'),
		  array('id' => '1454','name' => 'Osmaniye','country_id' => '216'),
		  array('id' => '1455','name' => 'Sakarya','country_id' => '216'),
		  array('id' => '1456','name' => 'Samsun','country_id' => '216'),
		  array('id' => '1457','name' => 'Sanliurfa','country_id' => '216'),
		  array('id' => '1458','name' => 'Siirt','country_id' => '216'),
		  array('id' => '1459','name' => 'Sivas','country_id' => '216'),
		  array('id' => '1460','name' => 'Tekirdag','country_id' => '216'),
		  array('id' => '1461','name' => 'Tokat','country_id' => '216'),
		  array('id' => '1462','name' => 'Trabzon','country_id' => '216'),
		  array('id' => '1463','name' => 'Usak','country_id' => '216'),
		  array('id' => '1464','name' => 'Van','country_id' => '216'),
		  array('id' => '1465','name' => 'Zonguldak','country_id' => '216'),
		  array('id' => '1466','name' => 'Funafuti','country_id' => '217'),
		  array('id' => '1468','name' => 'Changhwa','country_id' => '218'),
		  array('id' => '1469','name' => 'Chiayi','country_id' => '218'),
		  array('id' => '1470','name' => 'Hsinchu','country_id' => '218'),
		  array('id' => '1471','name' => 'Hualien','country_id' => '218'),
		  array('id' => '1472','name' => 'Ilan','country_id' => '218'),
		  array('id' => '1473','name' => 'Kaohsiung','country_id' => '218'),
		  array('id' => '1474','name' => 'Keelung','country_id' => '218'),
		  array('id' => '1475','name' => 'Miaoli','country_id' => '218'),
		  array('id' => '1476','name' => 'Nantou','country_id' => '218'),
		  array('id' => '1477','name' => 'Pingtung','country_id' => '218'),
		  array('id' => '1478','name' => 'Taichung','country_id' => '218'),
		  array('id' => '1479','name' => 'Tainan','country_id' => '218'),
		  array('id' => '1480','name' => 'Taipei','country_id' => '218'),
		  array('id' => '1481','name' => 'Taitung','country_id' => '218'),
		  array('id' => '1482','name' => 'Taoyuan','country_id' => '218'),
		  array('id' => '1483','name' => 'YÃ¼nlin','country_id' => '218'),
		  array('id' => '1484','name' => 'Arusha','country_id' => '219'),
		  array('id' => '1485','name' => 'Dar es Salaam','country_id' => '219'),
		  array('id' => '1486','name' => 'Dodoma','country_id' => '219'),
		  array('id' => '1487','name' => 'Kilimanjaro','country_id' => '219'),
		  array('id' => '1488','name' => 'Mbeya','country_id' => '219'),
		  array('id' => '1489','name' => 'Morogoro','country_id' => '219'),
		  array('id' => '1490','name' => 'Mwanza','country_id' => '219'),
		  array('id' => '1491','name' => 'Tabora','country_id' => '219'),
		  array('id' => '1492','name' => 'Tanga','country_id' => '219'),
		  array('id' => '1493','name' => 'Zanzibar West','country_id' => '219'),
		  array('id' => '1494','name' => 'Central','country_id' => '220'),
		  array('id' => '1495','name' => 'Dnipropetrovsk','country_id' => '221'),
		  array('id' => '1496','name' => 'Donetsk','country_id' => '221'),
		  array('id' => '1497','name' => 'Harkova','country_id' => '221'),
		  array('id' => '1498','name' => 'Herson','country_id' => '221'),
		  array('id' => '1499','name' => 'Hmelnytskyi','country_id' => '221'),
		  array('id' => '1500','name' => 'Ivano-Frankivsk','country_id' => '221'),
		  array('id' => '1501','name' => 'Kiova','country_id' => '221'),
		  array('id' => '1502','name' => 'Kirovograd','country_id' => '221'),
		  array('id' => '1503','name' => 'Krim','country_id' => '221'),
		  array('id' => '1504','name' => 'Lugansk','country_id' => '221'),
		  array('id' => '1505','name' => 'Lviv','country_id' => '221'),
		  array('id' => '1506','name' => 'Mykolajiv','country_id' => '221'),
		  array('id' => '1507','name' => 'Odesa','country_id' => '221'),
		  array('id' => '1508','name' => 'Pultava','country_id' => '221'),
		  array('id' => '1509','name' => 'Rivne','country_id' => '221'),
		  array('id' => '1510','name' => 'Sumy','country_id' => '221'),
		  array('id' => '1511','name' => 'Taka-Karpatia','country_id' => '221'),
		  array('id' => '1512','name' => 'Ternopil','country_id' => '221'),
		  array('id' => '1513','name' => 'TÅ¡erkasy','country_id' => '221'),
		  array('id' => '1514','name' => 'TÅ¡ernigiv','country_id' => '221'),
		  array('id' => '1515','name' => 'TÅ¡ernivtsi','country_id' => '221'),
		  array('id' => '1516','name' => 'Vinnytsja','country_id' => '221'),
		  array('id' => '1517','name' => 'Volynia','country_id' => '221'),
		  array('id' => '1518','name' => 'Zaporizzja','country_id' => '221'),
		  array('id' => '1519','name' => 'Zytomyr','country_id' => '221'),
		  array('id' => '1520','name' => 'Montevideo','country_id' => '223'),
		  array('id' => '1521','name' => 'Alabama','country_id' => '224'),
		  array('id' => '1522','name' => 'Alaska','country_id' => '224'),
		  array('id' => '1523','name' => 'Arizona','country_id' => '224'),
		  array('id' => '1524','name' => 'Arkansas','country_id' => '224'),
		  array('id' => '1525','name' => 'California','country_id' => '224'),
		  array('id' => '1526','name' => 'Colorado','country_id' => '224'),
		  array('id' => '1527','name' => 'Connecticut','country_id' => '224'),
		  array('id' => '1528','name' => 'District of Columbia','country_id' => '224'),
		  array('id' => '1529','name' => 'Florida','country_id' => '224'),
		  array('id' => '1530','name' => 'Georgia','country_id' => '224'),
		  array('id' => '1531','name' => 'Hawaii','country_id' => '224'),
		  array('id' => '1532','name' => 'Idaho','country_id' => '224'),
		  array('id' => '1533','name' => 'Illinois','country_id' => '224'),
		  array('id' => '1534','name' => 'Indiana','country_id' => '224'),
		  array('id' => '1535','name' => 'Iowa','country_id' => '224'),
		  array('id' => '1536','name' => 'Kansas','country_id' => '224'),
		  array('id' => '1537','name' => 'Kentucky','country_id' => '224'),
		  array('id' => '1538','name' => 'Louisiana','country_id' => '224'),
		  array('id' => '1539','name' => 'Maryland','country_id' => '224'),
		  array('id' => '1540','name' => 'Massachusetts','country_id' => '224'),
		  array('id' => '1541','name' => 'Michigan','country_id' => '224'),
		  array('id' => '1542','name' => 'Minnesota','country_id' => '224'),
		  array('id' => '1543','name' => 'Mississippi','country_id' => '224'),
		  array('id' => '1544','name' => 'Missouri','country_id' => '224'),
		  array('id' => '1545','name' => 'Montana','country_id' => '224'),
		  array('id' => '1546','name' => 'Nebraska','country_id' => '224'),
		  array('id' => '1547','name' => 'Nevada','country_id' => '224'),
		  array('id' => '1548','name' => 'New Hampshire','country_id' => '224'),
		  array('id' => '1549','name' => 'New Jersey','country_id' => '224'),
		  array('id' => '1550','name' => 'New Mexico','country_id' => '224'),
		  array('id' => '1551','name' => 'New York','country_id' => '224'),
		  array('id' => '1552','name' => 'North Carolina','country_id' => '224'),
		  array('id' => '1553','name' => 'Ohio','country_id' => '224'),
		  array('id' => '1554','name' => 'Oklahoma','country_id' => '224'),
		  array('id' => '1555','name' => 'Oregon','country_id' => '224'),
		  array('id' => '1556','name' => 'Pennsylvania','country_id' => '224'),
		  array('id' => '1557','name' => 'Rhode Island','country_id' => '224'),
		  array('id' => '1558','name' => 'South Carolina','country_id' => '224'),
		  array('id' => '1559','name' => 'South Dakota','country_id' => '224'),
		  array('id' => '1560','name' => 'Tennessee','country_id' => '224'),
		  array('id' => '1561','name' => 'Texas','country_id' => '224'),
		  array('id' => '1562','name' => 'Utah','country_id' => '224'),
		  array('id' => '1563','name' => 'Virginia','country_id' => '224'),
		  array('id' => '1564','name' => 'Washington','country_id' => '224'),
		  array('id' => '1565','name' => 'Wisconsin','country_id' => '224'),
		  array('id' => '1566','name' => 'Andijon','country_id' => '225'),
		  array('id' => '1567','name' => 'Buhoro','country_id' => '225'),
		  array('id' => '1568','name' => 'Cizah','country_id' => '225'),
		  array('id' => '1569','name' => 'Fargona','country_id' => '225'),
		  array('id' => '1570','name' => 'Karakalpakistan','country_id' => '225'),
		  array('id' => '1571','name' => 'Khorazm','country_id' => '225'),
		  array('id' => '1572','name' => 'Namangan','country_id' => '225'),
		  array('id' => '1573','name' => 'Navoi','country_id' => '225'),
		  array('id' => '1574','name' => 'Qashqadaryo','country_id' => '225'),
		  array('id' => '1575','name' => 'Samarkand','country_id' => '225'),
		  array('id' => '1576','name' => 'Surkhondaryo','country_id' => '225'),
		  array('id' => '1577','name' => 'Toskent','country_id' => '225'),
		  array('id' => '1578','name' => 'Toskent Shahri','country_id' => '225'),
		  array('id' => '1579','name' => 'â€“','country_id' => '226'),
		  //array('id' => '1580','name' => 'St George','country_id' => '0'),
		  array('id' => '1582','name' => 'AnzoÃ¡tegui','country_id' => '228'),
		  array('id' => '1583','name' => 'Apure','country_id' => '228'),
		  array('id' => '1584','name' => 'Aragua','country_id' => '228'),
		  array('id' => '1585','name' => 'Barinas','country_id' => '228'),
		  array('id' => '1586','name' => 'BolÃ­var','country_id' => '228'),
		  array('id' => '1587','name' => 'Carabobo','country_id' => '228'),
		  array('id' => '1588','name' => 'Distrito Federal','country_id' => '228'),
		  array('id' => '1589','name' => 'FalcÃ³n','country_id' => '228'),
		  array('id' => '1590','name' => 'GuÃ¡rico','country_id' => '228'),
		  array('id' => '1591','name' => 'Lara','country_id' => '228'),
		  array('id' => '1592','name' => 'MÃ©rida','country_id' => '228'),
		  array('id' => '1593','name' => 'Miranda','country_id' => '228'),
		  array('id' => '1594','name' => 'Monagas','country_id' => '228'),
		  array('id' => '1595','name' => 'Portuguesa','country_id' => '228'),
		  array('id' => '1596','name' => 'Sucre','country_id' => '228'),
		  array('id' => '1597','name' => 'TÃ¡chira','country_id' => '228'),
		  array('id' => '1598','name' => 'Trujillo','country_id' => '228'),
		  array('id' => '1599','name' => 'Yaracuy','country_id' => '228'),
		  array('id' => '1600','name' => 'Zulia','country_id' => '228'),
		  array('id' => '1601','name' => 'Tortola','country_id' => '229'),
		  array('id' => '1602','name' => 'St Thomas','country_id' => '230'),
		  array('id' => '1603','name' => 'An Giang','country_id' => '231'),
		  array('id' => '1604','name' => 'Ba Ria-Vung Tau','country_id' => '231'),
		  array('id' => '1605','name' => 'Bac Thai','country_id' => '231'),
		  array('id' => '1606','name' => 'Binh Dinh','country_id' => '231'),
		  array('id' => '1607','name' => 'Binh Thuan','country_id' => '231'),
		  array('id' => '1608','name' => 'Can Tho','country_id' => '231'),
		  array('id' => '1609','name' => 'Dac Lac','country_id' => '231'),
		  array('id' => '1610','name' => 'Dong Nai','country_id' => '231'),
		  array('id' => '1611','name' => 'Haiphong','country_id' => '231'),
		  array('id' => '1612','name' => 'Hanoi','country_id' => '231'),
		  array('id' => '1613','name' => 'Ho Chi Minh City','country_id' => '231'),
		  array('id' => '1614','name' => 'Khanh Hoa','country_id' => '231'),
		  array('id' => '1615','name' => 'Kien Giang','country_id' => '231'),
		  array('id' => '1616','name' => 'Lam Dong','country_id' => '231'),
		  array('id' => '1617','name' => 'Nam Ha','country_id' => '231'),
		  array('id' => '1618','name' => 'Nghe An','country_id' => '231'),
		  array('id' => '1619','name' => 'Quang Binh','country_id' => '231'),
		  array('id' => '1620','name' => 'Quang Nam-Da Nang','country_id' => '231'),
		  array('id' => '1621','name' => 'Quang Ninh','country_id' => '231'),
		  array('id' => '1622','name' => 'Thua Thien-Hue','country_id' => '231'),
		  array('id' => '1623','name' => 'Tien Giang','country_id' => '231'),
		  array('id' => '1624','name' => 'Shefa','country_id' => '232'),
		  array('id' => '1625','name' => 'Wallis','country_id' => '233'),
		  array('id' => '1626','name' => 'Upolu','country_id' => '234'),
		  array('id' => '1627','name' => 'Aden','country_id' => '235'),
		  array('id' => '1628','name' => 'Hadramawt','country_id' => '235'),
		  array('id' => '1629','name' => 'Hodeida','country_id' => '235'),
		  array('id' => '1630','name' => 'Ibb','country_id' => '235'),
		  array('id' => '1631','name' => 'Sanaa','country_id' => '235'),
		  array('id' => '1632','name' => 'Taizz','country_id' => '235'),
		  array('id' => '1633','name' => 'Central Serbia','country_id' => '236'),
		  array('id' => '1634','name' => 'Kosovo and Metohija','country_id' => '236'),
		  array('id' => '1635','name' => 'Montenegro','country_id' => '236'),
		  array('id' => '1636','name' => 'Vojvodina','country_id' => '236'),
		  array('id' => '1637','name' => 'Eastern Cape','country_id' => '237'),
		  array('id' => '1638','name' => 'Free State','country_id' => '237'),
		  array('id' => '1639','name' => 'Gauteng','country_id' => '237'),
		  array('id' => '1640','name' => 'KwaZulu-Natal','country_id' => '237'),
		  array('id' => '1641','name' => 'Mpumalanga','country_id' => '237'),
		  array('id' => '1642','name' => 'North West','country_id' => '237'),
		  array('id' => '1643','name' => 'Northern Cape','country_id' => '237'),
		  array('id' => '1644','name' => 'Western Cape','country_id' => '237'),
		  array('id' => '1645','name' => 'Central','country_id' => '238'),
		  array('id' => '1646','name' => 'Copperbelt','country_id' => '238'),
		  array('id' => '1647','name' => 'Lusaka','country_id' => '238'),
		  array('id' => '1648','name' => 'Bulawayo','country_id' => '239'),
		  array('id' => '1649','name' => 'Harare','country_id' => '239'),
		  array('id' => '1650','name' => 'Manicaland','country_id' => '239'),
		  array('id' => '1651','name' => 'Midlands','country_id' => '239')
		);
		
		DB::table('states')->insert($states);
	}
}
